onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - oxlint

overrides:
  defu@<=6.1.4: '>=6.1.5'
  esbuild@<0.28.1: '>=0.28.1'
  hono@<4.12.25: '>=4.12.25'
  js-yaml@<=4.1.1: '>=4.2.0'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: ^8.5.10
  qs@>=6.11.1 <=6.15.1: ^6.15.2
  smol-toml@<1.6.1: '>=1.6.1'
  vite@<7.3.5: '>=7.3.5'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
