import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { catalogRuleIds } from "../src/commands/rules.js";
import { parseConfig } from "../src/config/schema.js";
import { detectHardcodedConfigLiterals } from "../src/engines/ai-slop/hardcoded-config.js";
import type { EngineContext } from "../src/engines/types.js";

let temporaryDirectory: string;

const makeContext = (files: string[], repeatedLiteralThreshold?: number): EngineContext => ({
	rootDirectory: temporaryDirectory,
	languages: ["python"],
	frameworks: ["none"],
	files,
	installedTools: {},
	config: {
		quality: {
			maxFunctionLoc: 80,
			maxFileLoc: 400,
			maxNesting: 5,
			maxParams: 6,
			...(repeatedLiteralThreshold === undefined ? {} : { repeatedLiteralThreshold }),
		},
		security: { audit: true, auditTimeout: 25000 },
	},
});

const writeFile = (filename: string, content: string): string => {
	const filePath = path.join(temporaryDirectory, filename);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, content, "utf-8");
	return filePath;
};

const repeatedPythonCalls = (name: string, value: string, count: number): string[] =>
	Array.from(
		{ length: count },
		(_element, index) => `responses.append(requests.get(urls[${index}], ${name}=${value}))`,
	);

const repeatedLiteralMatches = (
	diagnostics: Awaited<ReturnType<typeof detectHardcodedConfigLiterals>>,
) => diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal");

beforeEach(() => {
	temporaryDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "aislop-repeated-literals-"));
});

afterEach(() => {
	fs.rmSync(temporaryDirectory, { recursive: true, force: true });
});

describe("repeated magic literals", () => {
	it("reports one finding for 28 repeated Python keyword arguments", async () => {
		const repeatedCalls = repeatedPythonCalls("timeout", "10", 28);
		const filePath = writeFile("gitea.py", repeatedCalls.join("\n"));

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));
		const matches = diagnostics.filter(
			(diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal",
		);

		expect(matches).toHaveLength(1);
		expect(matches[0].message).toContain("10");
		expect(matches[0].message).toContain("timeout");
		expect(matches[0].message).toContain("28");
	});

	it("does not report calls that reference a named constant", async () => {
		const filePath = writeFile(
			"constant.py",
			[
				"_DEFAULT_TIMEOUT_SECONDS = 10",
				...repeatedPythonCalls("timeout", "_DEFAULT_TIMEOUT_SECONDS", 28),
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("groups the same value separately by parameter name", async () => {
		const filePath = writeFile(
			"separate.py",
			[...repeatedPythonCalls("timeout", "10", 3), ...repeatedPythonCalls("retries", "10", 3)].join(
				"\n",
			),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("does not inspect test files", async () => {
		const filePath = writeFile(
			"client_test.py",
			repeatedPythonCalls("timeout", "10", 8).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("does not inspect generated files", async () => {
		const filePath = writeFile(
			"generated.py",
			[
				"# This file is generated by a schema tool.",
				...repeatedPythonCalls("timeout", "10", 8),
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("ignores universally trivial numeric values", async () => {
		const filePath = writeFile("trivial.py", Array.from({ length: 30 }, () => "x = 0").join("\n"));

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("reports repeated standalone Python assignment literals", async () => {
		const filePath = writeFile(
			"assignments.py",
			Array.from({ length: 4 }, () => "timeout = 10").join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated Python keyword literals in expressions that only start and end with calls", async () => {
		const filePath = writeFile(
			"compound-expressions.py",
			Array.from({ length: 4 }, () => "request(timeout=10) + response()").join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated Python keyword literals in unterminated call expressions", async () => {
		const filePath = writeFile(
			"unterminated-calls.py",
			Array.from({ length: 4 }, () => "request(timeout=10").join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated Python lambda defaults inside calls", async () => {
		const filePath = writeFile(
			"lambda-defaults.py",
			Array.from({ length: 4 }, () => "client.configure(lambda value, timeout=10: timeout)").join(
				"\n",
			),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated Python constructor calls appended as table rows", async () => {
		const filePath = writeFile(
			"appended-entries.py",
			Array.from({ length: 4 }, () => "entries.append(Entry(timeout=10))").join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("honors a configured occurrence threshold", async () => {
		const filePath = writeFile("strict.py", repeatedPythonCalls("timeout", "10", 2).join("\n"));

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 1));
		const matches = diagnostics.filter(
			(diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal",
		);

		expect(matches).toHaveLength(1);
		expect(matches[0].message).toContain("2");
	});

	it("reports repeated short Python string literals", async () => {
		const filePath = writeFile(
			"region.py",
			repeatedPythonCalls("region", '"us-west"', 4).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));
		const matches = diagnostics.filter(
			(diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal",
		);

		expect(matches).toHaveLength(1);
		expect(matches[0].message).toContain("us-west");
	});

	it("reports repeated raw Python string literals", async () => {
		const filePath = writeFile(
			"raw-region.py",
			repeatedPythonCalls("region", 'r"us-west"', 4).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports repeated Python floats with no leading digit", async () => {
		const filePath = writeFile(
			"fractional-timeout.py",
			repeatedPythonCalls("timeout", ".5", 4).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("keeps distinct Python integers above the safe integer limit in separate groups", async () => {
		const filePath = writeFile(
			"identifiers.py",
			[
				...repeatedPythonCalls("identifier", "9007199254740992", 2),
				...repeatedPythonCalls("identifier", "9007199254740993", 2),
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("does not group real and complex Python numeric literals together", async () => {
		const filePath = writeFile(
			"complex-phase.py",
			[...repeatedPythonCalls("phase", "10", 2), ...repeatedPythonCalls("phase", "10j", 2)].join(
				"\n",
			),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("does not group Python integer and floating-point literals together", async () => {
		const filePath = writeFile(
			"numeric-kinds.py",
			[
				...repeatedPythonCalls("timeout", "10", 2),
				...repeatedPythonCalls("timeout", "10.0", 2),
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("does not treat repeated literal examples inside Python strings as code", async () => {
		const filePath = writeFile(
			"documentation.py",
			[
				'first = "use timeout=10 when developing"',
				'second = "use timeout=10 when developing"',
				'third = "use timeout=10 when developing"',
				'fourth = "use timeout=10 when developing"',
				'notes = """',
				"timeout=10",
				"timeout=10",
				"timeout=10",
				"timeout=10",
				'"""',
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
	});

	it("reports repeated TypeScript option literals passed to calls", async () => {
		const filePath = writeFile(
			"client.ts",
			Array.from({ length: 4 }, () => "clients.push(createClient({ timeout: 10 }));").join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));
		const matches = diagnostics.filter(
			(diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal",
		);

		expect(matches).toHaveLength(1);
		expect(matches[0].message).toContain("timeout");
	});

	it("reports repeated nested TypeScript option literals passed to calls", async () => {
		const filePath = writeFile(
			"nested-client.ts",
			Array.from(
				{ length: 4 },
				() => "clients.push(createClient({ retry: { timeout: 10 } }));",
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));
		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated literals in standalone nested option objects", async () => {
		const filePath = writeFile(
			"cluster.ts",
			Array.from(
				{ length: 4 },
				(_element, index) => `const profile${index} = { retry: { timeout: 10 } };`,
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports a TypeScript object lookup table read through Object.keys", async () => {
		const filePath = writeFile(
			"status.ts",
			[
				"const statusOptions = {",
				"  pending: { timeout: 10 },",
				"  active: { timeout: 10 },",
				"  done: { timeout: 10 },",
				"  failed: { timeout: 10 },",
				"};",
				"Object.keys(statusOptions);",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("does not report a lookup table whose rows carry different values", async () => {
		// The load-bearing guard for the whole design: differing values never group.
		const filePath = writeFile(
			"varied.ts",
			[
				"const statusOptions = {",
				"  pending: { timeout: 10 },",
				"  active: { timeout: 30 },",
				"  done: { timeout: 45 },",
				"  failed: { timeout: 60 },",
				"};",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toEqual([]);
	});

	it("reports repeated keyword literals in Python dictionary rows", async () => {
		const filePath = writeFile(
			"entries.py",
			[
				"ENTRIES = {",
				...["pending", "active", "done", "failed"].map(
					(name) => `    "${name}": Entry(timeout=10),`,
				),
				"}",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated keyword literals in multiline Python dictionary rows", async () => {
		const filePath = writeFile(
			"multiline-entries.py",
			[
				"ENTRIES = {",
				...["pending", "active", "done", "failed"].flatMap((name) => [
					`    "${name}": Entry(`,
					"        timeout=10,",
					"    ),",
				]),
				"}",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated keyword literals in a Python list-backed table", async () => {
		const filePath = writeFile(
			"entry-list.py",
			[
				"ENTRIES = [",
				"    Entry(timeout=10),",
				"    Entry(timeout=10),",
				"    Entry(timeout=10),",
				"    Entry(timeout=10),",
				"]",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated keyword literals below prefixed Python string keys", async () => {
		const filePath = writeFile(
			"prefixed-entries.py",
			[
				"ENTRIES = {",
				'    r"pending": Entry(timeout=10),',
				'    u"active": Entry(timeout=10),',
				'    b"done": Entry(timeout=10),',
				'    br"failed": Entry(timeout=10),',
				"}",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated keyword literals below empty Python string keys", async () => {
		const filePath = writeFile(
			"empty-key-entries.py",
			[
				"ENTRIES = {",
				'    "": Entry(timeout=10),',
				'    "": Entry(timeout=10),',
				'    "": Entry(timeout=10),',
				'    "": Entry(timeout=10),',
				"}",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated nested properties in one TypeScript call argument", async () => {
		const filePath = writeFile(
			"cluster.ts",
			[
				"createCluster({",
				"  primary: { timeout: 10 },",
				"  secondary: { timeout: 10 },",
				"  tertiary: { timeout: 10 },",
				"  fallback: { timeout: 10 },",
				"});",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports top-level TypeScript option literals passed to constructors", async () => {
		const filePath = writeFile(
			"direct-constructed-client.ts",
			Array.from({ length: 4 }, () => "const client = new Client({ timeout: 10 });").join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated nested TypeScript option literals passed to constructors", async () => {
		const filePath = writeFile(
			"constructed-client.ts",
			Array.from(
				{ length: 4 },
				() => "const client = new Client({ retry: { timeout: 10 } });",
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated properties in standalone nested TypeScript objects", async () => {
		const filePath = writeFile(
			"nested-service-options.ts",
			Array.from(
				{ length: 4 },
				(_element, index) => `const serviceOptions${index} = { retry: { timeout: 10 } };`,
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated values in a TypeScript array literal", async () => {
		const filePath = writeFile(
			"lookup.ts",
			[
				"const statusTable = [",
				'  { name: "pending", timeout: 10 },',
				'  { name: "active", timeout: 10 },',
				'  { name: "paused", timeout: 10 },',
				'  { name: "stopped", timeout: 10 },',
				"];",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports repeated values in a TypeScript object lookup table", async () => {
		const filePath = writeFile(
			"object-lookup.ts",
			[
				"const statusTable = {",
				"  pending: { timeout: 10 },",
				"  active: { timeout: 10 },",
				"  paused: { timeout: 10 },",
				"  stopped: { timeout: 10 },",
				"};",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports repeated values in a spread-composed TypeScript lookup table", async () => {
		const filePath = writeFile(
			"spread-object-lookup.ts",
			[
				"const sharedRows = getSharedRows();",
				"const statusTable = {",
				"  ...sharedRows,",
				"  pending: { timeout: 10 },",
				"  active: { timeout: 10 },",
				"  paused: { timeout: 10 },",
				"  stopped: { timeout: 10 },",
				"};",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports a TypeScript object lookup table passed to a read-only consumer", async () => {
		const filePath = writeFile(
			"consumed-object-lookup.ts",
			[
				"const statusTable = {",
				"  pending: { timeout: 10 },",
				"  active: { timeout: 10 },",
				"  paused: { timeout: 10 },",
				"  stopped: { timeout: 10 },",
				"};",
				"Object.keys(statusTable);",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports call-wrapped rows in a TypeScript lookup table", async () => {
		const filePath = writeFile(
			"call-wrapped-object-lookup.ts",
			[
				"const statusTable = {",
				"  pending: createEntry({ timeout: 10 }),",
				"  active: createEntry({ timeout: 10 }),",
				"  paused: createEntry({ timeout: 10 }),",
				"  stopped: createEntry({ timeout: 10 }),",
				"};",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath], 3));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports enum-like records pushed into a data collection", async () => {
		const filePath = writeFile(
			"presentation.ts",
			Array.from(
				{ length: 4 },
				(_element, index) => `steps.push({ emphasis: "primary", label: "Step ${index}" });`,
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports an inline TypeScript lookup table read through Object.keys", async () => {
		const filePath = writeFile(
			"inline-object-lookup.ts",
			[
				"Object.keys({",
				"  pending: { timeout: 10 },",
				"  active: { timeout: 10 },",
				"  paused: { timeout: 10 },",
				"  stopped: { timeout: 10 },",
				"});",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated TypeScript discriminant properties", async () => {
		const filePath = writeFile(
			"result.ts",
			Array.from(
				{ length: 4 },
				(_element, index) => `function result${index}() { return { kind: "invalid" }; }`,
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports records inserted into a TypeScript lookup map", async () => {
		const filePath = writeFile(
			"lookup-map.ts",
			Array.from(
				{ length: 4 },
				(_element, index) => `statusTable.set("status-${index}", { timeout: 10 });`,
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(
			diagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});

	it("reports direct object arguments passed to TypeScript member calls", async () => {
		const filePath = writeFile(
			"registered-entries.ts",
			Array.from({ length: 4 }, () => "registry.register({ timeout: 10 });").join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports direct object arguments passed through element access", async () => {
		const filePath = writeFile(
			"element-access-entries.ts",
			Array.from({ length: 4 }, () => 'rows["push"]({ timeout: 10 });').join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports runtime options even when the property is named type", async () => {
		const filePath = writeFile(
			"remote-client.ts",
			Array.from({ length: 4 }, () => 'createClient({ type: "remote" });').join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated properties in standalone TypeScript objects", async () => {
		const filePath = writeFile(
			"service-options.ts",
			Array.from(
				{ length: 4 },
				(_element, index) => `const serviceOptions${index} = { timeout: 10 };`,
			).join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));
		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports repeated Python keyword literals in real call shapes (assignment, return, multiline continuation)", async () => {
		// Regression for issue #2: the motivating file (a Gitea REST client) never
		// uses a standalone call-expression statement. Every call site is an
		// assignment target, a `return` expression, or a multi-line call with the
		// keyword argument on a continuation line. An earlier revision of the rule
		// gated candidates on statement shape and reported zero findings against
		// the real file for that reason.
		const filePath = writeFile(
			"gitea_client.py",
			[
				"def whoami(self):",
				"    r = httpx.get(url, headers=self._headers(), timeout=10, verify=True)",
				"    return r.json()",
				"",
				"def _write(self, verb, url, **kwargs):",
				"    send = getattr(httpx, verb)",
				"    return send(url, headers=self._headers(), timeout=10, verify=True, **kwargs)",
				"",
				"def list_open_prs(self, owner, repo):",
				"    r = httpx.get(",
				"        url,",
				"        headers=self._headers(),",
				"        timeout=10,",
				"        verify=True,",
				"        params=params,",
				"    )",
				"    return r.json()",
				"",
				"def get_pr(self, owner, repo, pr_number):",
				"    r = httpx.get(url, headers=self._headers(), timeout=10, verify=True)",
				"    return r.json()",
			].join("\n"),
		);

		const diagnostics = await detectHardcodedConfigLiterals(makeContext([filePath]));

		expect(repeatedLiteralMatches(diagnostics)).toHaveLength(1);
	});

	it("reports only after the default threshold is exceeded", async () => {
		const threeOccurrencePath = writeFile(
			"three.py",
			repeatedPythonCalls("timeout", "10", 3).join("\n"),
		);
		const fourOccurrencePath = writeFile(
			"four.py",
			repeatedPythonCalls("timeout", "10", 4).join("\n"),
		);

		const threeDiagnostics = await detectHardcodedConfigLiterals(
			makeContext([threeOccurrencePath]),
		);
		const fourDiagnostics = await detectHardcodedConfigLiterals(makeContext([fourOccurrencePath]));

		expect(
			threeDiagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toEqual([]);
		expect(
			fourDiagnostics.filter((diagnostic) => diagnostic.rule === "ai-slop/repeated-magic-literal"),
		).toHaveLength(1);
	});
});

describe("repeated magic literal configuration", () => {
	it("defaults the permitted occurrence threshold to three", () => {
		expect(parseConfig({}).quality.repeatedLiteralThreshold).toBe(3);
	});

	it("accepts a configured permitted occurrence threshold", () => {
		expect(
			parseConfig({ quality: { repeatedLiteralThreshold: 5 } }).quality.repeatedLiteralThreshold,
		).toBe(5);
	});

	it("registers the rule in the built-in catalog", () => {
		expect(catalogRuleIds()).toContain("ai-slop/repeated-magic-literal");
	});
});
