import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { loadConfig } from "../src/config/index.js";
import { isAutoGenerated } from "../src/utils/source-files.js";

// ─── isAutoGenerated — file descriptor safety ────────────────────────────────

describe("isAutoGenerated — FD safety", () => {
	let tmpDir: string;

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "aislop-fd-test-"));
	});

	afterEach(() => {
		fs.rmSync(tmpDir, { recursive: true, force: true });
	});

	it("returns true for auto-generated files", () => {
		const filePath = path.join(tmpDir, "generated.ts");
		fs.writeFileSync(filePath, "// auto-generated by tool\nexport const x = 1;");
		expect(isAutoGenerated(filePath)).toBe(true);
	});

	it("returns true for common gen output directories", () => {
		const filePath = path.join(tmpDir, "src-tauri", "gen", "apple", "assets", "bundle.js");
		fs.mkdirSync(path.dirname(filePath), { recursive: true });
		fs.writeFileSync(filePath, "export const generatedAsset = true;\n");
		expect(isAutoGenerated(filePath)).toBe(true);
	});

	it("does not treat ordinary hand-written gen directories as auto-generated", () => {
		const filePath = path.join(tmpDir, "src", "gen", "helpers.ts");
		fs.mkdirSync(path.dirname(filePath), { recursive: true });
		fs.writeFileSync(filePath, "export const helper = true;\n");
		expect(isAutoGenerated(filePath)).toBe(false);
	});

	it("returns false for normal files", () => {
		const filePath = path.join(tmpDir, "normal.ts");
		fs.writeFileSync(filePath, "export const x = 1;\nexport const y = 2;");
		expect(isAutoGenerated(filePath)).toBe(false);
	});

	it("returns false for non-existent files without throwing", () => {
		expect(isAutoGenerated(path.join(tmpDir, "nope.ts"))).toBe(false);
	});

	it("returns false for paths that cannot be read as a file (no FD leak)", () => {
		// A directory: openSync succeeds but readSync throws EISDIR on every OS,
		// exercising the catch/finally that must still close the descriptor.
		const dirPath = path.join(tmpDir, "a-directory");
		fs.mkdirSync(dirPath);

		expect(isAutoGenerated(dirPath)).toBe(false);
	});

	it("handles many files without exhausting FDs", () => {
		const files: string[] = [];
		for (let i = 0; i < 200; i++) {
			const filePath = path.join(tmpDir, `file${i}.ts`);
			fs.writeFileSync(
				filePath,
				`// ${i % 2 === 0 ? "auto-generated" : "normal"}\nexport const x = ${i};`,
			);
			files.push(filePath);
		}

		let errors = 0;
		for (const f of files) {
			try {
				isAutoGenerated(f);
			} catch {
				errors++;
			}
		}
		expect(errors).toBe(0);
	});
});

// ─── loadConfig — warning on invalid YAML ────────────────────────────────────

describe("loadConfig — invalid config handling", () => {
	let tmpDir: string;

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "aislop-config-warn-test-"));
	});

	afterEach(() => {
		fs.rmSync(tmpDir, { recursive: true, force: true });
	});

	it("returns defaults for invalid YAML and writes warning to stderr", () => {
		const configDir = path.join(tmpDir, ".aislop");
		fs.mkdirSync(configDir, { recursive: true });
		fs.writeFileSync(path.join(configDir, "config.yml"), "invalid: yaml: [[[");

		const stderrChunks: string[] = [];
		const origWrite = process.stderr.write.bind(process.stderr);
		process.stderr.write = (chunk: unknown) => {
			stderrChunks.push(String(chunk));
			return true;
		};

		try {
			const config = loadConfig(tmpDir);
			// Should return defaults
			expect(config.engines.format).toBe(true);
			expect(config.engines.lint).toBe(true);
		} finally {
			process.stderr.write = origWrite;
		}

		const stderr = stderrChunks.join("");
		expect(stderr).toContain("Failed to parse");
		expect(stderr).toContain("Using default configuration");
	});

	it("returns defaults when config dir does not exist", () => {
		const config = loadConfig(tmpDir);
		expect(config.engines.format).toBe(true);
	});
});
