import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { runOxlint } from "../../src/engines/lint/oxlint.js";
import type { EngineContext } from "../../src/engines/types.js";

let tmpDir: string;

const writeFile = (relativePath: string, content: string): string => {
	const absolutePath = path.join(tmpDir, relativePath);
	fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
	fs.writeFileSync(absolutePath, content, "utf-8");
	return absolutePath;
};

const context = (): EngineContext => ({
	rootDirectory: tmpDir,
	languages: ["typescript"],
	frameworks: ["react"],
	installedTools: { oxlint: true },
	config: {
		quality: { maxFunctionLoc: 80, maxFileLoc: 400, maxNesting: 5, maxParams: 6 },
		security: { audit: false, auditTimeout: 0 },
		lint: { typecheck: false },
	},
});

describe("runOxlint project context", () => {
	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "aislop-oxlint-context-"));
		writeFile("package.json", JSON.stringify({ name: "demo", dependencies: {} }));
		writeFile(
			"tsconfig.json",
			JSON.stringify({
				compilerOptions: {
					target: "ES2022",
					module: "ESNext",
					jsx: "preserve",
					jsxImportSource: "solid-js",
				},
				include: ["src", "packages"],
			}),
		);
	});

	afterEach(() => {
		fs.rmSync(tmpDir, { recursive: true, force: true });
	});

	it("uses filtered source files and generated ambient globals", async () => {
		writeFile(
			"biome.json",
			JSON.stringify({
				files: {
					includes: ["**", "!packages/ui-solid/src/auto-imports.d.ts"],
				},
			}),
		);
		writeFile(
			"packages/ui-solid/src/auto-imports.d.ts",
			[
				"/* eslint-disable */",
				"// Generated by unplugin-auto-import",
				"export {}",
				"declare global {",
				"  const IconCapLogo: unknown",
				"}",
			].join("\n"),
		);
		writeFile("src/app.tsx", "export const App = () => <IconCapLogo />;\n");
		writeFile("src/app.test.ts", "missingTestGlobal();\n");

		const diagnostics = await runOxlint(context());

		expect(diagnostics.some((d) => d.message.includes("IconCapLogo"))).toBe(false);
		expect(diagnostics.some((d) => d.filePath.endsWith("app.test.ts"))).toBe(false);
	});

	it("recognizes globals from nested SST config files", async () => {
		writeFile(
			"infra/sst.config.ts",
			"export default $config({ app() { return { home: 'aws' }; } });\n",
		);
		writeFile(
			"src/infra.ts",
			[
				"export const wire = () => {",
				"  if ($app.stage === 'production') return aws.s3;",
				"  return $interpolate`stage-${$app.stage}`;",
				"};",
			].join("\n"),
		);

		const diagnostics = await runOxlint(context());

		expect(diagnostics.some((d) => d.rule === "eslint/no-undef")).toBe(false);
	});

	it("recognizes runtime globals without hiding them outside their scope", async () => {
		writeFile("bun.lock", "");
		writeFile("src/bun.ts", "export const launch = () => Bun.spawn(['echo', 'ok']);\n");
		writeFile(
			"supabase/functions/update-check/index.ts",
			"Deno.serve(() => new Response('ok'));\n",
		);
		writeFile("src/not-deno.ts", "export const env = Deno.env.get('MODE');\n");
		writeFile(
			"extension/manifest.json",
			JSON.stringify({
				manifest_version: 3,
				background: { service_worker: "background.js" },
			}),
		);
		writeFile(
			"extension/background.js",
			"chrome.runtime.onInstalled.addListener(() => undefined);\n",
		);
		writeFile("src/not-extension.ts", "chrome.runtime.sendMessage({ type: 'ping' });\n");

		const diagnostics = await runOxlint(context());

		expect(diagnostics.some((d) => d.message.includes("'Bun' is not defined"))).toBe(false);
		expect(
			diagnostics.some(
				(d) =>
					d.filePath.endsWith("supabase/functions/update-check/index.ts") &&
					d.message.includes("'Deno' is not defined"),
			),
		).toBe(false);
		expect(
			diagnostics.some(
				(d) =>
					d.filePath.endsWith("extension/background.js") &&
					d.message.includes("'chrome' is not defined"),
			),
		).toBe(false);
		expect(
			diagnostics.some(
				(d) =>
					d.filePath.endsWith("src/not-deno.ts") && d.message.includes("'Deno' is not defined"),
			),
		).toBe(true);
		expect(
			diagnostics.some(
				(d) =>
					d.filePath.endsWith("src/not-extension.ts") &&
					d.message.includes("'chrome' is not defined"),
			),
		).toBe(true);
	});

	it("drops Solid JSX ref assignment false positives without disabling real no-undef", async () => {
		writeFile(
			"src/app.tsx",
			[
				"export const App = () => {",
				"  let input!: HTMLInputElement;",
				"  return <input ref={input} value={missingValue} />;",
				"};",
			].join("\n"),
		);

		const diagnostics = await runOxlint(context());

		expect(diagnostics.some((d) => d.message.includes("'input' is always 'undefined'"))).toBe(
			false,
		);
		expect(diagnostics.some((d) => d.message.includes("missingValue"))).toBe(true);
	});
});
