import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import {
	GO_DECL_START,
	JAVA_DECL_START,
	JAVA_DECL_START_FALLBACK,
	PHP_DECL_START,
	RUBY_DECL_START,
	RUST_DECL_START,
} from "./narrative-comments-patterns.js";
import { isNonProductionPath, isToolingConfigFile } from "./non-production-paths.js";

const TRIVIAL_VERB_STEMS =
	"Import|Defin|Initializ|Setting|Set\\s+up|Setup|Return|Check|Loop|Iterat|Creat|Updat|Delet|Remov|Handl|Get|Fetch|Increment|Decrement|Writ|Runn|Run|Pars|Execut|Extract|Sav|Load|Build|Start|Stopp|Stop|Clean(?:up|\\s+up)?|Configur|Validat|Process|Queue|Fire|Emit|Dispatch|Log|Print|Render";

const TRIVIAL_JS_COMMENT_PATTERNS = [
	// "This function does X" when the declaration name already says X
	/\/\/\s*This (?:function|method|class|variable|constant) (?:will |is used to |is responsible for )?/i,
	// "Verb[ing/s] ..." or bare "// Verb" imperative.
	new RegExp(`\\/\\/\\s*(?:${TRIVIAL_VERB_STEMS})(?:e|es|ing|s)?\\b`, "i"),
];

const TRIVIAL_PYTHON_COMMENT_PATTERNS = [
	/^#\s*This (?:function|method|class) (?:will |is used to )?/i,
	new RegExp(`^#\\s*(?:${TRIVIAL_VERB_STEMS})(?:e|es|ing|s)?\\b`, "i"),
];

// Keywords that indicate a comment adds context (a reason or condition), not just restating the
// code: explanatory markers plus conditionals/necessity words ("... if X", "needs to ...").
const EXPLANATORY_KEYWORDS =
	/\b(?:because|since|note|todo|fixme|hack|warn|warning|workaround|caveat|important|assumes?|if|when|unless|until|only|except|otherwise|needs?|must|should|ensure|avoid|prevent|requires?)\b/i;

// Characters that suggest commented-out code rather than prose
const COMMENTED_CODE_CHARS = /[({=;}\]>]/;

const MAX_TRIVIAL_COMMENT_LENGTH = 60;

const isJsComment = (trimmed: string): boolean =>
	trimmed.startsWith("//") && !trimmed.startsWith("///") && !trimmed.startsWith("//!");
const isPythonComment = (trimmed: string): boolean =>
	trimmed.startsWith("#") && !trimmed.startsWith("#!");

const isLineComment = (trimmed: string): boolean =>
	isJsComment(trimmed) || isPythonComment(trimmed);

// Removing one line out of a consecutive comment run would mangle the surrounding prose.
const isInMultiLineCommentRun = (lines: string[], index: number): boolean => {
	const prev = index > 0 ? lines[index - 1].trim() : "";
	const next = index + 1 < lines.length ? lines[index + 1].trim() : "";
	return isLineComment(prev) || isLineComment(next);
};

/**
 * Extract just the comment text after the comment marker.
 */
const getCommentBody = (trimmed: string): string => {
	if (trimmed.startsWith("//")) return trimmed.slice(2).trim();
	if (trimmed.startsWith("#")) return trimmed.slice(1).trim();
	return trimmed;
};

const isTrivialComment = (trimmed: string, nextLine: string | undefined): boolean => {
	const isJs = isJsComment(trimmed);
	const isPy = isPythonComment(trimmed);
	if (!isJs && !isPy) return false;

	const commentBody = getCommentBody(trimmed);

	// Skip long comments — they likely contain meaningful context
	if (commentBody.length > MAX_TRIVIAL_COMMENT_LENGTH) return false;

	// Skip comments with explanatory keywords
	if (EXPLANATORY_KEYWORDS.test(commentBody)) return false;

	// Skip parenthetical explanations like "(excluding ignored directories)"
	if (commentBody.includes("(") && commentBody.includes(")")) return false;

	// Skip commented-out code (contains code-like characters)
	if (COMMENTED_CODE_CHARS.test(commentBody)) return false;

	// Skip section dividers (followed by a blank line)
	if (nextLine !== undefined && nextLine.trim() === "") return false;

	// Skip section divider / header comments (contain box-drawing or repeated dashes)
	if (/[─━═╌╍┄┅│┃]/.test(commentBody)) return false;
	if (/^-{3,}|─{3,}/.test(commentBody)) return false;

	// Now check against the actual trivial patterns
	const patterns = isJs ? TRIVIAL_JS_COMMENT_PATTERNS : TRIVIAL_PYTHON_COMMENT_PATTERNS;
	return patterns.some((pattern) => pattern.test(trimmed));
};

const declStartForExt = (ext: string): RegExp[] => {
	switch (ext) {
		case ".go":
			return [GO_DECL_START];
		case ".rs":
			return [RUST_DECL_START];
		case ".rb":
			return [RUBY_DECL_START];
		case ".java":
			return [JAVA_DECL_START, JAVA_DECL_START_FALLBACK];
		case ".php":
			return [PHP_DECL_START];
		default:
			return [];
	}
};

const isCommentLineForExt = (line: string, ext: string): boolean => {
	const trimmed = line.trim();
	if (ext === ".rb") return trimmed.startsWith("#") && !trimmed.startsWith("#!");
	if (ext === ".go" || ext === ".rs" || ext === ".java" || ext === ".php") {
		return trimmed.startsWith("//") || trimmed.startsWith("#");
	}
	return false;
};

const isDocCommentForDeclaration = (lines: string[], lineIdx: number, ext: string): boolean => {
	const patterns = declStartForExt(ext);
	if (patterns.length === 0) return false;
	for (let j = lineIdx + 1; j < lines.length; j++) {
		const candidate = lines[j];
		if (candidate.trim() === "") continue;
		if (isCommentLineForExt(candidate, ext)) continue;
		return patterns.some((re) => re.test(candidate));
	}
	return false;
};

/**
 * Heuristic: many real (non-slop) short comments in bundler/build configs are just
 * section labels right above rule objects (e.g. "// Vue SFC" above `test: /\.vue$/`).
 * These were responsible for very high trivial-comment volume in OSS benchmarks.
 * We still allow other ai-slop rules on these files.
 */
const isLikelyConfigSectionLabel = (trimmed: string, nextLine: string | undefined): boolean => {
	if (!nextLine) return false;
	const body = getCommentBody(trimmed).toLowerCase().trim();
	const next = nextLine.trim();

	// Common config rule keys in bundlers (webpack, vite, rollup, next, etc.)
	const configRuleRe =
		/^(test|use|loader|rules|plugins|resolve|module|build|server|optimizeDeps|defineConfig|config):\s*[[\x7b]/;
	if (configRuleRe.test(next)) return true;

	// Property assignment like test: /... or use: ['...']
	if (/\b(test|use|loader)\s*:\s*["'/\x5b]/.test(next)) return true;

	// Generic short label before object key in config (e.g. // Build styles \n css: {...} or rules: )
	if (/^[a-zA-Z0-9_$-]+\s*:\s*[[\x7b]/.test(next) && body.length < 30) {
		return true;
	}

	// Very short imperative labels at top level of config objects
	if (
		/^\/\/\s*(Vue|React|Build|Styles|Scripts|Assets|Images|Fonts|Icons)/i.test(trimmed) &&
		/:\s*\x7b/.test(next)
	) {
		return true;
	}

	return false;
};

const scanFileForTrivialComments = (
	content: string,
	relativePath: string,
	ext: string,
): Diagnostic[] => {
	const diagnostics: Diagnostic[] = [];
	const lines = content.split("\n");
	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i].trim();
		const nextLine = i + 1 < lines.length ? lines[i + 1] : undefined;
		if (!isTrivialComment(trimmed, nextLine)) continue;
		if (isInMultiLineCommentRun(lines, i)) continue;
		if (isDocCommentForDeclaration(lines, i, ext)) continue;

		// Contextual skip for common non-slop label comments in build/tooling configs.
		// This targets the high-volume FP cases from benchmarks (e.g. "// Vue SFC" above test: rules)
		// while still allowing detection of real trivial comments inside actual JS logic in the same file.
		if (isToolingConfigFile(relativePath) && isLikelyConfigSectionLabel(trimmed, nextLine)) {
			continue;
		}

		diagnostics.push({
			filePath: relativePath,
			engine: "ai-slop",
			rule: "ai-slop/trivial-comment",
			severity: "warning",
			message: "Trivial comment that restates the code",
			help: "Remove comments that don't add information beyond what the code already expresses",
			line: i + 1,
			column: 0,
			category: "AI Slop",
			fixable: true,
		});
	}
	return diagnostics;
};

export const detectTrivialComments = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		const ext = path.extname(filePath);
		const relativePath = path.relative(context.rootDirectory, filePath);
		if (isNonProductionPath(relativePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		diagnostics.push(...scanFileForTrivialComments(content, relativePath, ext));
	}

	return diagnostics;
};
