import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const CPP_EXTENSIONS = new Set([".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"]);
const HEADER_EXTENSIONS = new Set([".h", ".hh", ".hpp", ".hxx"]);
// Excludes .c and .h so legitimate C code is never flagged for C-style casts etc.
const CPP_ONLY_EXTENSIONS = new Set([".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx"]);

const LINE_COMMENT_RE = /^\s*\/\//;
const MAIN_RE = /\bint\s+main\s*\(/;

type Scope = "all" | "header" | "cppOnly";

interface LineRule {
	rule: string;
	regex: RegExp;
	message: string;
	help: string;
	scope: Scope;
	skipInMain?: boolean;
}

const LINE_RULES: LineRule[] = [
	{
		rule: "ai-slop/cpp-not-implemented",
		regex: /\bthrow\s+std::(?:logic_error|runtime_error)\s*\(\s*"[^"]*not\s+implemented/i,
		message: 'Stub throws "not implemented"',
		help: "Implement the function or remove the stub before shipping",
		scope: "all",
	},
	{
		rule: "ai-slop/cpp-not-implemented",
		regex: /\bassert\s*\(\s*(?:false|0)\s*&&\s*"[^"]*not\s+implemented/i,
		message: 'Stub asserts "not implemented"',
		help: "Implement the function or remove the stub before shipping",
		scope: "all",
	},
	{
		rule: "ai-slop/cpp-using-namespace-std-in-header",
		regex: /^\s*using\s+namespace\s+std\s*;/,
		message: "`using namespace std;` at header scope leaks into every includer",
		help: "Qualify names with std:: or move the using-directive into a .cpp",
		scope: "header",
	},
	{
		rule: "ai-slop/cpp-c-style-cast",
		regex:
			/\(\s*(?:unsigned\s+|signed\s+|const\s+)?(?:int|char|short|long|float|double|bool|size_t|uint\d+_t|int\d+_t)\s*\*?\s*\)\s*[A-Za-z_(]/,
		message: "C-style cast in C++; prefer static_cast / reinterpret_cast",
		help: "Use a named C++ cast so the intent and safety of the conversion are explicit",
		scope: "cppOnly",
	},
	{
		rule: "ai-slop/cpp-manual-delete",
		regex: /\bdelete\s*(?:\[\s*\])?\s+[A-Za-z_][\w:.>-]*/,
		message: "Manual delete; prefer a smart pointer or RAII container",
		help: "Own the resource with std::unique_ptr / std::vector so it frees automatically",
		scope: "all",
	},
	{
		rule: "ai-slop/cpp-iostream-leftover",
		regex: /\bstd::c(?:out|err)\b/,
		message: "std::cout / std::cerr left in library code",
		help: "Remove debug output or route it through the project's logging facility",
		scope: "all",
		skipInMain: true,
	},
];

const pushFinding = (
	out: Diagnostic[],
	relPath: string,
	rule: string,
	lineIndex: number,
	message: string,
	help: string,
): void => {
	out.push({
		filePath: relPath,
		engine: "ai-slop",
		rule,
		severity: "warning",
		message,
		help,
		line: lineIndex + 1,
		column: 1,
		category: "AI Slop",
		fixable: false,
	});
};

export const detectCppPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFiles(context).filter((f) =>
		CPP_EXTENSIONS.has(path.extname(f).toLowerCase()),
	);
	const out: Diagnostic[] = [];

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const ext = path.extname(filePath).toLowerCase();
		const isHeader = HEADER_EXTENSIONS.has(ext);
		const isCppOnly = CPP_ONLY_EXTENSIONS.has(ext);
		const hasMain = MAIN_RE.test(content);
		const relPath = relativePosix(context.rootDirectory, filePath);
		const lines = content.split("\n");

		for (let i = 0; i < lines.length; i++) {
			const line = lines[i];
			if (LINE_COMMENT_RE.test(line)) continue;
			for (const r of LINE_RULES) {
				if (r.scope === "header" && !isHeader) continue;
				if (r.scope === "cppOnly" && !isCppOnly) continue;
				if (r.skipInMain && hasMain) continue;
				if (r.regex.test(line)) pushFinding(out, relPath, r.rule, i, r.message, r.help);
			}
		}
	}
	return out;
};
