import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const CSHARP_EXTENSIONS = new Set([".cs"]);

const LINE_COMMENT_RE = /^\s*\/\//;
const NOT_IMPLEMENTED_RE = /\bthrow\s+new\s+NotImplementedException\s*\(/;

// XML-doc summaries that merely restate the member: "Gets/Sets the X", "The X.", etc.
const TRIVIAL_SUMMARY_RE = /^(?:gets?(?:\s+or\s+sets?)?|sets?|the|a|an)\b[\w\s]*\.?$/i;
const EXPLANATORY_KEYWORDS_RE =
	/\b(?:because|since|so that|note|todo|fixme|hack|warn|caveat|important|assumes?|e\.g\.|i\.e\.|when|unless|must|avoid)\b/i;
const SUMMARY_INLINE_RE = /<summary>\s*(.*?)\s*<\/summary>/i;

// True when the regex match sits inside a `//` line comment on that line.
const isInLineComment = (line: string, matchIndex: number): boolean => {
	const commentIndex = line.indexOf("//");
	return commentIndex !== -1 && commentIndex < matchIndex;
};

const flagNotImplemented = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (LINE_COMMENT_RE.test(lines[i])) continue;
		const match = NOT_IMPLEMENTED_RE.exec(lines[i]);
		if (!match) continue;
		if (isInLineComment(lines[i], match.index)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/csharp-not-implemented",
			severity: "warning",
			message:
				"`throw new NotImplementedException()` is almost certainly a stub the agent forgot to fill in.",
			help: "Implement the method, or if the work is genuinely deferred, file a ticket and reference it in a comment so it doesn't ship invisibly.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

// Extract the text of a single-line `/// <summary>...</summary>`, else null.
const inlineSummaryText = (line: string): string | null => {
	const trimmed = line.trim();
	if (!trimmed.startsWith("///")) return null;
	const match = SUMMARY_INLINE_RE.exec(trimmed);
	return match ? match[1].trim() : null;
};

const flagRedundantDoc = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const summary = inlineSummaryText(lines[i]);
		if (summary === null || summary.length === 0) continue;
		if (EXPLANATORY_KEYWORDS_RE.test(summary)) continue;
		if (!TRIVIAL_SUMMARY_RE.test(summary)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/csharp-redundant-doc-comment",
			severity: "warning",
			message: "XML-doc summary restates the member name without adding information.",
			help: 'Delete the doc comment, or replace boilerplate ("Gets or sets the X") with the *why* — constraints, units, invariants a reader can\'t infer from the signature.',
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

export const detectCSharpPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!CSHARP_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = path.relative(context.rootDirectory, filePath);
		const lines = content.split("\n");
		flagNotImplemented(lines, relPath, diagnostics);
		flagRedundantDoc(lines, relPath, diagnostics);
	}

	return diagnostics;
};
