import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import { buildOutputTypeResolver, type OutputTypeResolver } from "../dotnet-output-type.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { isNonProductionPath } from "./non-production-paths.js";

const CSHARP_EXTENSIONS = new Set([".cs"]);

const LINE_COMMENT_RE = /^\s*\/\//;
const NOT_IMPLEMENTED_RE = /\bthrow\s+new\s+NotImplementedException\s*\(/;

const ASYNC_VOID_RE = /\basync\s+void\s+(\w+)\s*\(/;
// Event-handler shapes that legitimately use async void.
const EVENT_HANDLER_NAME_RE = /^(?:On[A-Z]|.*Handler$|.*_\w+$)/;
const EVENT_ARGS_RE = /\bEventArgs\b/;

const SYNC_OVER_ASYNC_RE =
	/\.(?:Result\b|Wait\s*\(\s*\)|GetAwaiter\s*\(\s*\)\s*\.\s*GetResult\s*\(\s*\))/;

const SYNC_INTENT_LOOKBACK = 2;

// XML-doc summaries that merely restate the member: "Gets/Sets the X", "The X.", etc.
const TRIVIAL_SUMMARY_RE = /^(?:gets?(?:\s+or\s+sets?)?|sets?|the|a|an)\b[\w\s]*\.?$/i;
const EXPLANATORY_KEYWORDS_RE =
	/\b(?:because|since|so that|note|todo|fixme|hack|warn|caveat|important|assumes?|e\.g\.|i\.e\.|when|unless|must|avoid)\b/i;
const SUMMARY_INLINE_RE = /<summary>\s*(.*?)\s*<\/summary>/i;

// Shared shape for every C# finding — keeps each rule to its detection logic.
const pushFinding = (
	out: Diagnostic[],
	relPath: string,
	rule: string,
	lineIndex: number,
	message: string,
	help: string,
): void => {
	out.push({
		filePath: relPath,
		engine: "ai-slop",
		rule,
		severity: "warning",
		message,
		help,
		line: lineIndex + 1,
		column: 1,
		category: "AI Slop",
		fixable: false,
	});
};

// True when the regex match sits inside a `//` line comment on that line.
const isInLineComment = (line: string, matchIndex: number): boolean => {
	const commentIndex = line.indexOf("//");
	return commentIndex !== -1 && commentIndex < matchIndex;
};

const hasIntentComment = (lines: string[], lineIndex: number): boolean => {
	for (let j = lineIndex - 1; j >= Math.max(0, lineIndex - SYNC_INTENT_LOOKBACK); j--) {
		if (LINE_COMMENT_RE.test(lines[j])) return true;
	}
	return false;
};

// Scan each non-comment line against `regex`; emit a finding when it matches and
// the optional `accept` guard (extra context-sensitive checks) returns true.
const scanLineMatches = (
	lines: string[],
	relPath: string,
	out: Diagnostic[],
	regex: RegExp,
	rule: string,
	message: string,
	help: string,
	accept?: (match: RegExpExecArray, lineIndex: number) => boolean,
): void => {
	for (let i = 0; i < lines.length; i++) {
		if (LINE_COMMENT_RE.test(lines[i])) continue;
		const match = regex.exec(lines[i]);
		if (!match) continue;
		if (accept && !accept(match, i)) continue;
		pushFinding(out, relPath, rule, i, message, help);
	}
};

// Extract the text of a single-line `/// <summary>...</summary>`, else null.
const inlineSummaryText = (line: string): string | null => {
	const trimmed = line.trim();
	if (!trimmed.startsWith("///")) return null;
	const match = SUMMARY_INLINE_RE.exec(trimmed);
	return match ? match[1].trim() : null;
};

// Redundant XML-doc lives on `///` lines, which scanLineMatches would skip as
// comments — so it gets its own pass.
const flagRedundantDoc = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const summary = inlineSummaryText(lines[i]);
		if (summary === null || summary.length === 0) continue;
		if (EXPLANATORY_KEYWORDS_RE.test(summary)) continue;
		if (!TRIVIAL_SUMMARY_RE.test(summary)) continue;
		pushFinding(
			out,
			relPath,
			"ai-slop/csharp-redundant-doc-comment",
			i,
			"XML-doc summary restates the member name without adding information.",
			'Delete the doc comment, or replace boilerplate ("Gets or sets the X") with the *why* — constraints, units, invariants a reader can\'t infer from the signature.',
		);
	}
};

const PRAGMA_DISABLE_RE = /#pragma\s+warning\s+disable\b/;
const PRAGMA_RESTORE_RE = /#pragma\s+warning\s+restore\b/;
const SUPPRESS_MESSAGE_RE = /\bSuppressMessage\s*\(/;
const JUSTIFICATION_RE = /Justification\s*=\s*"([^"]*)"/i;
// Justifications the IDE/agents auto-insert that carry no real reason.
const PLACEHOLDER_JUSTIFICATION_RE = /^(?:<pending>|pending|todo|)$/i;

// True when a `//` comment exists anywhere on the line (trailing justification).
const hasTrailingComment = (line: string): boolean => line.includes("//");

// True when the nearest non-blank line above is a `//` comment (preceding justification).
const precededByComment = (lines: string[], lineIndex: number): boolean => {
	for (let j = lineIndex - 1; j >= 0; j--) {
		const trimmed = lines[j].trim();
		if (trimmed === "") continue;
		return trimmed.startsWith("//");
	}
	return false;
};

// Suppressing a warning without saying why is the canonical move to make a
// finding vanish - no analyzer can flag its own suppression.
const flagSuppressedWarnings = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		const trimmed = line.trim();
		if (trimmed.startsWith("//")) continue;

		if (PRAGMA_DISABLE_RE.test(line) && !PRAGMA_RESTORE_RE.test(line)) {
			if (hasTrailingComment(line) || precededByComment(lines, i)) continue;
			pushFinding(
				out,
				relPath,
				"ai-slop/csharp-suppressed-warning",
				i,
				"`#pragma warning disable` suppresses the warning without saying why.",
				"Fix the underlying warning. If suppression is genuinely justified, add a `//` comment naming the reason (and prefer a scoped disable/restore over a file-wide one).",
			);
			continue;
		}

		if (SUPPRESS_MESSAGE_RE.test(line)) {
			const match = JUSTIFICATION_RE.exec(line);
			const justified = match !== null && !PLACEHOLDER_JUSTIFICATION_RE.test(match[1].trim());
			if (justified) continue;
			pushFinding(
				out,
				relPath,
				"ai-slop/csharp-suppressed-warning",
				i,
				"`[SuppressMessage]` has no real Justification - it hides the analyzer finding.",
				"Fix the underlying issue, or fill Justification with the actual reason the suppression is safe (not the `<Pending>` placeholder).",
			);
		}
	}
};

// A catch whose entire body is `throw;` - matched after collapsing whitespace so
// both the single-line and multi-line forms hit. The `\{\s*throw\s*;\s*\}` tail
// requires `throw;` to be the ONLY statement (any preceding stmt or `throw new`
// breaks the match), so log-then-rethrow and wrap-and-rethrow are not flagged.
const CATCH_ONLY_THROW_RE = /\bcatch\b\s*(?:\([^)]*\))?\s*\{\s*throw\s*;\s*\}/;

// `catch (...) { throw; }` catches and immediately rethrows - pure noise.
const flagEmptyCatchRethrow = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (lines[i].trim().startsWith("//")) continue;
		if (!/\bcatch\b/.test(lines[i])) continue;
		// Join a short window so the multi-line `catch {\n throw;\n}` form collapses
		// onto one string the regex can match.
		const window = lines
			.slice(i, i + 5)
			.join(" ")
			.replace(/\s+/g, " ");
		if (!CATCH_ONLY_THROW_RE.test(window)) continue;
		pushFinding(
			out,
			relPath,
			"ai-slop/csharp-empty-catch-rethrow",
			i,
			"`catch (...) { throw; }` catches and immediately rethrows - it does nothing but add noise.",
			"Remove the try/catch if you're not handling the exception; use `finally` for cleanup, or `throw new ...(..., ex)` to add context.",
		);
	}
};

// The null-forgiving operator: a postfix `!` on an expression (identifier, `)`,
// or `]`) followed by `.`/`;`/`,`/`)`/`]`/`}`/whitespace/EOL. The required
// following char set excludes `=`, so `!=` never matches; requiring an
// identifier/`)`/`]` immediately before excludes prefix `!x` and `!!`. `!` inside
// a string usually precedes `"` (not in the follow set), so `"done!"` is excluded.
// Deferred / known limitation: Entity-Framework `= null!` and use-site `!` right
// after a manual null check are legitimate but still flag here (high-recall by
// decision); proper carve-outs await a contributor who uses those patterns.
const NULL_FORGIVING_RE = /[\w)\]]!(?=[\s.;,)\]}]|$)/;

// Null-forgiving `!` silences the nullable warning without proving non-null.
const flagNullForgiving = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	scanLineMatches(
		lines,
		relPath,
		out,
		NULL_FORGIVING_RE,
		"ai-slop/csharp-null-forgiving",
		"The null-forgiving `!` silences the nullable warning without proving the value is non-null.",
		"Handle the null case (guard, `??`, or throw with context) instead of asserting non-null. Use `!` only when non-null is provable, and say why.",
		(match, i) => !isInLineComment(lines[i], match.index),
	);
};

const DEBUG_TRACE_RE = /\b(?:Debug|Trace)\.(?:Write|WriteLine|WriteIf|WriteLineIf)\s*\(/;
const CONSOLE_OUT_RE = /\bConsole\.(?:Write|WriteLine)\s*\(/;
// Writing to stderr is deliberate status output (the C# `console.error`), never flagged.
const CONSOLE_ERROR_RE = /\bConsole\.Error\b/;

// A file-level `// aislop-worker` comment marks a child-process worker whose
// stdout IS its IPC protocol (the parent reads results from stdout). It exempts
// ONLY the Console.Write* (stdout) scan; Debug/Trace output stays flagged because
// those are still leftovers, not part of the contract.
const WORKER_MARKER_RE = /^\s*\/\/\s*aislop-worker\b/;
const isWorkerFile = (lines: string[]): boolean =>
	lines.some((line) => WORKER_MARKER_RE.test(line));

// Debug/Trace output is flagged everywhere (minus non-production paths). `Console.*`
// stdout writes are flagged only in library projects - in an Exe (console app)
// stdout IS the product. `Console.Error.*` (stderr) is always intentional. Mirrors
// the JS console-leftover heuristic in dead-patterns.ts.
const flagConsoleLeftover = (
	lines: string[],
	relPath: string,
	absolutePath: string,
	outputTypes: OutputTypeResolver,
	out: Diagnostic[],
): void => {
	if (isNonProductionPath(relPath)) return;

	scanLineMatches(
		lines,
		relPath,
		out,
		DEBUG_TRACE_RE,
		"ai-slop/csharp-console-leftover",
		"Debug/Trace output left in shipped code is usually a leftover.",
		"Remove the diagnostic write, or route it through the project's logger.",
	);

	if (outputTypes.isExeProject(absolutePath)) return;
	// An IPC worker's stdout is its protocol, not a leftover - skip the Console scan.
	if (isWorkerFile(lines)) return;
	scanLineMatches(
		lines,
		relPath,
		out,
		CONSOLE_OUT_RE,
		"ai-slop/csharp-console-leftover",
		"`Console.Write*` in a library writes to stdout - almost always a leftover.",
		"Remove it or route through the project's logger. (In a console app, or a file marked `// aislop-worker`, this rule doesn't fire.)",
		(_match, i) => !CONSOLE_ERROR_RE.test(lines[i]),
	);
};

// --- Idiom-level rules (cf. the Python idiom layer) -------------------------

const IF_LADDER_THRESHOLD = 4;

// `catch (Exception ...)` / `catch (System.Exception ...)` - the broadest typed
// catch. A `when (...)` filter is a deliberate narrowing and is exempt.
const BROAD_CATCH_RE = /\bcatch\s*\(\s*(?:System\.)?Exception\b/;
const CATCH_WHEN_FILTER_RE = /\bwhen\b/;
const BROAD_CATCH_EMPTY_RE = /\bcatch\b\s*\(\s*(?:System\.)?Exception\b[^)]*\)\s*\{\s*\}/;
// The caught exception variable, when the clause declares one (`catch (Exception ex)`).
const BROAD_CATCH_VAR_RE = /\bcatch\s*\(\s*(?:System\.)?Exception\s+([A-Za-z_]\w*)\s*\)/;
// The `catch (...) {` opening, allowing the brace on a following line (Allman style).
const CATCH_BODY_OPEN_RE = /\bcatch\s*\([^)]*\)\s*\{/;

// Body of a `{ ... }` block by brace matching from its opening brace. Interpolation
// braces in `$"..."` are balanced so naive counting handles them; a lone brace inside
// a string or char literal is the only mis-count risk and is vanishingly rare in a
// catch body.
const extractBlockBody = (content: string, openBraceIndex: number): string | null => {
	let depth = 0;
	for (let i = openBraceIndex; i < content.length; i++) {
		const character = content[i];
		if (character === "{") depth += 1;
		else if (character === "}") {
			depth -= 1;
			if (depth === 0) return content.slice(openBraceIndex + 1, i);
		}
	}
	return null;
};

// A broad catch surfaces (rather than buries) the error when its body references the
// caught exception variable - logging it, wrapping it, or otherwise keeping the failure
// diagnosable. This is the same bar python-broad-except applies: it flags only silent
// `pass` bodies, not logged ones. A catch with no variable, or one whose variable is
// never used, drops the error and stays flagged. The variable is block-scoped, so the
// body is brace-matched to avoid crediting a reference in a sibling catch.
const broadCatchSurfacesError = (lines: string[], catchLineIndex: number): boolean => {
	const variableMatch = BROAD_CATCH_VAR_RE.exec(lines[catchLineIndex]);
	if (!variableMatch) return false;
	const content = lines.slice(catchLineIndex).join("\n");
	const openMatch = CATCH_BODY_OPEN_RE.exec(content);
	if (!openMatch) return false;
	const openBraceIndex = openMatch.index + openMatch[0].length - 1;
	const body = extractBlockBody(content, openBraceIndex);
	if (body === null) return false;
	return new RegExp(`\\b${variableMatch[1]}\\b`).test(body);
};

// A broad `catch (Exception)` that drops the failure buries problems you didn't plan
// for. Empty and pure-rethrow broad catches are covered by swallowed-exception and
// csharp-empty-catch-rethrow; a catch-and-log boundary (the body references the caught
// exception) is observable recovery, matching python-broad-except - so skip those here.
const flagBroadCatch = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (lines[i].trim().startsWith("//")) continue;
		if (!BROAD_CATCH_RE.test(lines[i])) continue;
		if (CATCH_WHEN_FILTER_RE.test(lines[i])) continue;
		const window = lines
			.slice(i, i + 5)
			.join(" ")
			.replace(/\s+/g, " ");
		if (CATCH_ONLY_THROW_RE.test(window)) continue;
		if (BROAD_CATCH_EMPTY_RE.test(window)) continue;
		if (broadCatchSurfacesError(lines, i)) continue;
		pushFinding(
			out,
			relPath,
			"ai-slop/csharp-broad-catch",
			i,
			"`catch (Exception)` catches everything and drops the failure - the specific problems you didn't plan for vanish.",
			"Catch the specific exception type(s) you can handle and let the rest propagate. At a deliberate boundary, log the caught exception (or add a `when` filter) so the failure stays diagnosable instead of disappearing.",
		);
	}
};

// `.Count() <op> 0|1` (or the reversed form) - enumerating a sequence just to ask
// "are there any?". `\b[01]\b` avoids matching the digits inside larger numbers.
const LINQ_COUNT_RE =
	/\.Count\s*\(\s*\)\s*(?:==|!=|>=|<=|>|<)\s*\b[01]\b|\b[01]\b\s*(?:==|!=|>=|<=|>|<)\s*[A-Za-z_][\w.]*\.Count\s*\(\s*\)/;

const flagLinqCount = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	scanLineMatches(
		lines,
		relPath,
		out,
		LINQ_COUNT_RE,
		"ai-slop/csharp-linq-count",
		"`.Count()` compared to 0/1 walks the whole sequence just to ask whether any element exists.",
		"Use `.Any()` (or `!collection.Any()` for the empty check) instead of `.Count() > 0` / `.Count() == 0`.",
		(match, i) => !isInLineComment(lines[i], match.index),
	);
};

// Index `for` loop walking `.Length`/`.Count` with the same counter throughout -
// the canonical shape that reads more clearly as `foreach`.
const INDEX_FOR_RE =
	/\bfor\s*\(\s*(?:int|long|uint|nint|var)\s+(\w+)\s*=\s*0\s*;\s*\1\s*<\s*[A-Za-z_][\w.]*\.(?:Length|Count)\b[^;]*;\s*\1\s*(?:\+\+|\+=\s*1)/;

// Body of the `for` loop starting on `forLineIndex`, whether a `{ }` block or a single
// braceless statement. The header's own parentheses (e.g. a `.Count()` call) are matched
// past before the body is read.
const extractLoopBody = (lines: string[], forLineIndex: number): string | null => {
	const content = lines.slice(forLineIndex).join("\n");
	const forIndex = content.search(/\bfor\s*\(/);
	if (forIndex === -1) return null;
	let depth = 0;
	let i = content.indexOf("(", forIndex);
	for (; i < content.length; i++) {
		if (content[i] === "(") depth += 1;
		else if (content[i] === ")") {
			depth -= 1;
			if (depth === 0) {
				i += 1;
				break;
			}
		}
	}
	while (i < content.length && /\s/.test(content[i])) i += 1;
	if (content[i] === "{") return extractBlockBody(content, i);
	const semicolon = content.indexOf(";", i);
	return semicolon === -1 ? content.slice(i) : content.slice(i, semicolon + 1);
};

// True when the loop counter is only ever a `collection[index]` subscript - the shape a
// `foreach` expresses more clearly. If the index is used for anything else (a nested
// `j = i + 1` look-ahead, arithmetic, logging, an argument), `foreach` cannot express it,
// so the loop is left alone. Mirrors the rule's own "if the index itself is used, ignore
// this" guidance, which the line-only match could not honor.
const indexUsedOnlyForElementAccess = (
	lines: string[],
	forLineIndex: number,
	indexName: string,
): boolean => {
	const body = extractLoopBody(lines, forLineIndex);
	if (body === null) return true;
	const withoutSubscripts = body.replace(new RegExp(`\\[\\s*${indexName}\\s*\\]`, "g"), "");
	return !new RegExp(`\\b${indexName}\\b`).test(withoutSubscripts);
};

const flagIndexLoop = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	scanLineMatches(
		lines,
		relPath,
		out,
		INDEX_FOR_RE,
		"ai-slop/csharp-index-loop",
		"Index `for` loop over `.Length`/`.Count` is usually clearer as `foreach`.",
		"Use `foreach (var item in collection)` when you don't need the index. If the index itself is used, ignore this.",
		(match, i) =>
			!isInLineComment(lines[i], match.index) && indexUsedOnlyForElementAccess(lines, i, match[1]),
	);
};

// if/else-if ladder comparing one value against constants - a switch in disguise.
const IF_LADDER_BRANCH_RE =
	/^\s*(?:\}\s*)?(?:else\s+)?if\s*\(\s*([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)\s*==\s*(?:"[^"]*"|'[^']*'|[\w.]+)\s*\)/;
const ELSE_IF_RE = /\belse\s+if\b/;

// Walk consecutive if/else-if branches that compare the SAME value; a chain of
// IF_LADDER_THRESHOLD+ is a switch (or handler map) wearing an if/else costume.
const flagIfLadder = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	let chainVariable: string | null = null;
	let count = 0;
	let startLine = 0;
	const finalize = (): void => {
		if (chainVariable !== null && count >= IF_LADDER_THRESHOLD) {
			pushFinding(
				out,
				relPath,
				"ai-slop/csharp-if-ladder",
				startLine,
				`${count} repeated if/else-if branches dispatch on \`${chainVariable}\`.`,
				"Use a `switch` (or a lookup/handler map) when each branch compares the same value against a constant.",
			);
		}
		chainVariable = null;
		count = 0;
	};
	for (let i = 0; i < lines.length; i++) {
		if (lines[i].trim().startsWith("//")) continue;
		const match = IF_LADDER_BRANCH_RE.exec(lines[i]);
		if (!match) continue;
		const variable = match[1];
		if (ELSE_IF_RE.test(lines[i]) && chainVariable === variable) {
			count++;
			continue;
		}
		finalize();
		chainVariable = variable;
		count = 1;
		startLine = i;
	}
	finalize();
};

// Strip string/char literals and the trailing line comment so braces or loop
// keywords *inside* them don't skew the brace-depth tracking below.
const stripStringsAndComments = (line: string): string =>
	line
		.replace(/@?\$?"(?:[^"\\]|\\.)*"/g, '""')
		.replace(/'(?:[^'\\]|\\.)'/g, "''")
		.replace(/\/\/.*$/, "");

const LOOP_HEADER_RE = /\b(?:for|foreach|while)\s*\(|\bdo\b/;
// `<name> += ... "<literal>"` - a `+=` whose right-hand side contains a string
// literal/interpolation, so we only flag concatenations we can SEE are string-typed.
const STRING_CONCAT_RE = /(\w+)\s*\+=\s*[^;]*"/;

// `s += "..."` inside a loop rebuilds the entire string each iteration (O(n^2)).
// Loop bodies are tracked by brace depth (strings/comments stripped first); the
// `{` may sit on the loop-header line or the next line, both handled.
const flagStringConcatInLoop = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	let braceDepth = 0;
	const loopBodyDepths: number[] = [];
	let pendingLoop = false;
	for (let i = 0; i < lines.length; i++) {
		const raw = lines[i];
		if (raw.trim().startsWith("//")) continue;
		const code = stripStringsAndComments(raw);

		if (loopBodyDepths.length > 0) {
			const match = STRING_CONCAT_RE.exec(raw);
			if (match && !isInLineComment(raw, match.index)) {
				pushFinding(
					out,
					relPath,
					"ai-slop/csharp-string-concat-in-loop",
					i,
					`\`${match[1]} += ...\` inside a loop reallocates the whole string each iteration (O(n^2)).`,
					"Build the result with a `StringBuilder` (append in the loop, `.ToString()` after) instead of `+=` concatenation.",
				);
			}
		}

		if (LOOP_HEADER_RE.test(code)) pendingLoop = true;

		let openedBrace = false;
		for (const char of code) {
			if (char === "{") {
				braceDepth++;
				openedBrace = true;
				if (pendingLoop) {
					loopBodyDepths.push(braceDepth);
					pendingLoop = false;
				}
			} else if (char === "}") {
				const idx = loopBodyDepths.indexOf(braceDepth);
				if (idx !== -1) loopBodyDepths.splice(idx, 1);
				if (braceDepth > 0) braceDepth--;
			}
		}
		// A single-statement loop body (`for (...) Foo();` with no `{`) - drop the
		// pending flag so it can't wrongly mark the next braced block as a loop.
		if (pendingLoop && !openedBrace && code.includes(";")) pendingLoop = false;
	}
};

export const detectCSharpPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);
	const outputTypes = buildOutputTypeResolver(context.rootDirectory);

	for (const filePath of files) {
		if (!CSHARP_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = relativePosix(context.rootDirectory, filePath);
		const lines = content.split("\n");

		scanLineMatches(
			lines,
			relPath,
			diagnostics,
			NOT_IMPLEMENTED_RE,
			"ai-slop/csharp-not-implemented",
			"`throw new NotImplementedException()` is almost certainly a stub the agent forgot to fill in.",
			"Implement the method, or if the work is genuinely deferred, file a ticket and reference it in a comment so it doesn't ship invisibly.",
			(match, i) => !isInLineComment(lines[i], match.index),
		);

		scanLineMatches(
			lines,
			relPath,
			diagnostics,
			ASYNC_VOID_RE,
			"ai-slop/csharp-async-void",
			"`async void` can't be awaited and its exceptions crash the process. Use `async Task` unless this is an event handler.",
			"Return `Task` so callers can await and observe exceptions. If it must be `void` (event handler), name it accordingly and guarantee it can't throw.",
			(match, i) => !EVENT_HANDLER_NAME_RE.test(match[1]) && !EVENT_ARGS_RE.test(lines[i]),
		);

		scanLineMatches(
			lines,
			relPath,
			diagnostics,
			SYNC_OVER_ASYNC_RE,
			"ai-slop/csharp-sync-over-async",
			"Blocking on a Task with `.Result`/`.Wait()`/`.GetAwaiter().GetResult()` risks deadlock and burns a thread.",
			"`await` the task instead. If you genuinely have a completed task and must block, add a short comment naming the invariant so this isn't read as accidental sync-over-async.",
			(_match, i) => !hasIntentComment(lines, i),
		);

		flagRedundantDoc(lines, relPath, diagnostics);
		flagSuppressedWarnings(lines, relPath, diagnostics);
		flagEmptyCatchRethrow(lines, relPath, diagnostics);
		flagNullForgiving(lines, relPath, diagnostics);
		flagConsoleLeftover(lines, relPath, filePath, outputTypes, diagnostics);
		flagBroadCatch(lines, relPath, diagnostics);
		flagLinqCount(lines, relPath, diagnostics);
		flagIndexLoop(lines, relPath, diagnostics);
		flagIfLadder(lines, relPath, diagnostics);
		flagStringConcatInLoop(lines, relPath, diagnostics);
	}

	return diagnostics;
};
