import fs from "node:fs";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const CSHARP_EXTENSIONS = new Set([".cs"]);

const LINE_COMMENT_RE = /^\s*\/\//;
const NOT_IMPLEMENTED_RE = /\bthrow\s+new\s+NotImplementedException\s*\(/;

const ASYNC_VOID_RE = /\basync\s+void\s+(\w+)\s*\(/;
// Event-handler shapes that legitimately use async void.
const EVENT_HANDLER_NAME_RE = /^(?:On[A-Z]|.*Handler$|.*_\w+$)/;
const EVENT_ARGS_RE = /\bEventArgs\b/;

const SYNC_OVER_ASYNC_RE =
	/\.(?:Result\b|Wait\s*\(\s*\)|GetAwaiter\s*\(\s*\)\s*\.\s*GetResult\s*\(\s*\))/;

const SYNC_INTENT_LOOKBACK = 2;

// XML-doc summaries that merely restate the member: "Gets/Sets the X", "The X.", etc.
const TRIVIAL_SUMMARY_RE = /^(?:gets?(?:\s+or\s+sets?)?|sets?|the|a|an)\b[\w\s]*\.?$/i;
const EXPLANATORY_KEYWORDS_RE =
	/\b(?:because|since|so that|note|todo|fixme|hack|warn|caveat|important|assumes?|e\.g\.|i\.e\.|when|unless|must|avoid)\b/i;
const SUMMARY_INLINE_RE = /<summary>\s*(.*?)\s*<\/summary>/i;

// True when the regex match sits inside a `//` line comment on that line.
const isInLineComment = (line: string, matchIndex: number): boolean => {
	const commentIndex = line.indexOf("//");
	return commentIndex !== -1 && commentIndex < matchIndex;
};

const flagNotImplemented = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (LINE_COMMENT_RE.test(lines[i])) continue;
		const match = NOT_IMPLEMENTED_RE.exec(lines[i]);
		if (!match) continue;
		if (isInLineComment(lines[i], match.index)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/csharp-not-implemented",
			severity: "warning",
			message:
				"`throw new NotImplementedException()` is almost certainly a stub the agent forgot to fill in.",
			help: "Implement the method, or if the work is genuinely deferred, file a ticket and reference it in a comment so it doesn't ship invisibly.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

// Extract the text of a single-line `/// <summary>...</summary>`, else null.
const inlineSummaryText = (line: string): string | null => {
	const trimmed = line.trim();
	if (!trimmed.startsWith("///")) return null;
	const match = SUMMARY_INLINE_RE.exec(trimmed);
	return match ? match[1].trim() : null;
};

const flagRedundantDoc = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const summary = inlineSummaryText(lines[i]);
		if (summary === null || summary.length === 0) continue;
		if (EXPLANATORY_KEYWORDS_RE.test(summary)) continue;
		if (!TRIVIAL_SUMMARY_RE.test(summary)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/csharp-redundant-doc-comment",
			severity: "warning",
			message: "XML-doc summary restates the member name without adding information.",
			help: 'Delete the doc comment, or replace boilerplate ("Gets or sets the X") with the *why* — constraints, units, invariants a reader can\'t infer from the signature.',
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

const hasIntentComment = (lines: string[], lineIndex: number): boolean => {
	for (let j = lineIndex - 1; j >= Math.max(0, lineIndex - SYNC_INTENT_LOOKBACK); j--) {
		if (LINE_COMMENT_RE.test(lines[j])) return true;
	}
	return false;
};

const flagAsyncVoid = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (LINE_COMMENT_RE.test(lines[i])) continue;
		const match = ASYNC_VOID_RE.exec(lines[i]);
		if (!match) continue;
		const name = match[1];
		if (EVENT_HANDLER_NAME_RE.test(name)) continue;
		if (EVENT_ARGS_RE.test(lines[i])) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/csharp-async-void",
			severity: "warning",
			message:
				"`async void` can't be awaited and its exceptions crash the process. Use `async Task` unless this is an event handler.",
			help: "Return `Task` so callers can await and observe exceptions. If it must be `void` (event handler), name it accordingly and guarantee it can't throw.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

const flagSyncOverAsync = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		if (LINE_COMMENT_RE.test(lines[i])) continue;
		if (!SYNC_OVER_ASYNC_RE.test(lines[i])) continue;
		if (hasIntentComment(lines, i)) continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/csharp-sync-over-async",
			severity: "warning",
			message:
				"Blocking on a Task with `.Result`/`.Wait()`/`.GetAwaiter().GetResult()` risks deadlock and burns a thread.",
			help: "`await` the task instead. If you genuinely have a completed task and must block, add a short comment naming the invariant so this isn't read as accidental sync-over-async.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

export const detectCSharpPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!CSHARP_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relPath = path.relative(context.rootDirectory, filePath);
		const lines = content.split("\n");
		flagNotImplemented(lines, relPath, diagnostics);
		flagRedundantDoc(lines, relPath, diagnostics);
		flagAsyncVoid(lines, relPath, diagnostics);
		flagSyncOverAsync(lines, relPath, diagnostics);
	}

	return diagnostics;
};
