import fs from "node:fs";
import { isBuiltin } from "node:module";
import path from "node:path";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { type AliasMatcher, collectTsPathAliases } from "./js-import-aliases.js";
import { collectWorkspaceDirs } from "./js-workspaces.js";
import { isNonProductionPath } from "./non-production-paths.js";
import { PYTHON_IMPORT_TO_PIP, PYTHON_STDLIB } from "./python-data.js";
import { collectPythonDeps, type PythonDependencyScope } from "./python-manifest.js";

const JS_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const PY_EXTENSIONS = new Set([".py"]);

interface JsDependencyScope {
	directory: string;
	jsDeps: Set<string>;
	packageName?: string;
}

interface PackageManifest {
	jsDeps: Set<string>;
	jsScopes: JsDependencyScope[];
	pyDeps: Set<string>;
	hasJsManifest: boolean;
	hasPyManifest: boolean;
	rootHasPyManifest: boolean;
	pyScopes: PythonDependencyScope[];
}

const readJson = (filePath: string): unknown => {
	try {
		return JSON.parse(fs.readFileSync(filePath, "utf-8"));
	} catch {
		return null;
	}
};

const PKG_DEP_SECTIONS = [
	"dependencies",
	"devDependencies",
	"peerDependencies",
	"optionalDependencies",
];

const addDepsFromPkg = (pkg: Record<string, unknown>, jsDeps: Set<string>): void => {
	for (const section of PKG_DEP_SECTIONS) {
		const deps = pkg[section];
		if (deps && typeof deps === "object") {
			for (const name of Object.keys(deps as Record<string, unknown>)) {
				jsDeps.add(name);
			}
		}
	}
};

const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", "out", "target", "coverage"]);

const mergeDeps = (target: Set<string>, source: Set<string>): void => {
	for (const dep of source) target.add(dep);
};

const collectJsScope = (directory: string): JsDependencyScope | null => {
	const pkgPath = path.join(directory, "package.json");
	if (!fs.existsSync(pkgPath)) return null;
	const pkg = readJson(pkgPath) as Record<string, unknown> | null;
	if (!pkg || typeof pkg !== "object") return null;
	const jsDeps = new Set<string>();
	addDepsFromPkg(pkg, jsDeps);
	const packageName = typeof pkg.name === "string" ? pkg.name : undefined;
	if (packageName) jsDeps.add(packageName);
	return { directory, jsDeps, packageName };
};

const collectJsScopes = (rootDir: string): JsDependencyScope[] => {
	const scopes: JsDependencyScope[] = [];
	const walk = (dir: string): void => {
		const scope = collectJsScope(dir);
		if (scope) scopes.push(scope);
		let entries: import("node:fs").Dirent[];
		try {
			entries = fs.readdirSync(dir, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			if (!entry.isDirectory()) continue;
			if (entry.name.startsWith(".") && entry.name !== ".github") continue;
			if (SKIP_DIRS.has(entry.name)) continue;
			walk(path.join(dir, entry.name));
		}
	};
	walk(rootDir);
	return scopes;
};

const collectJsDeps = (
	rootDir: string,
	jsDeps: Set<string>,
	jsScopes: JsDependencyScope[],
): boolean => {
	const pkgPath = path.join(rootDir, "package.json");
	if (!fs.existsSync(pkgPath)) return jsScopes.length > 0;
	const pkg = readJson(pkgPath) as Record<string, unknown> | null;
	if (!pkg || typeof pkg !== "object") return jsScopes.length > 0;

	for (const scope of jsScopes) {
		mergeDeps(jsDeps, scope.jsDeps);
	}

	const workspaceDirs = collectWorkspaceDirs(rootDir, pkg);
	for (const wsDir of workspaceDirs) {
		const wsPkg = readJson(path.join(wsDir, "package.json")) as Record<string, unknown> | null;
		if (!wsPkg) continue;
		if (typeof wsPkg.name === "string") jsDeps.add(wsPkg.name);
		addDepsFromPkg(wsPkg, jsDeps);
	}
	return true;
};

const loadManifest = (rootDir: string): PackageManifest => {
	const jsScopes = collectJsScopes(rootDir);
	const jsDeps = new Set<string>();
	const hasJsManifest = collectJsDeps(rootDir, jsDeps, jsScopes);
	const { pyDeps, hasPyManifest, rootHasPyManifest, scopes } = collectPythonDeps(rootDir);
	return {
		jsDeps,
		jsScopes,
		pyDeps,
		hasJsManifest,
		hasPyManifest,
		rootHasPyManifest,
		pyScopes: scopes,
	};
};

const isJsRelativeOrAbsolute = (spec: string): boolean =>
	spec.startsWith(".") || spec.startsWith("/") || spec.startsWith("~/");

const RUNTIME_BUILTINS = new Set(["bun"]);
const isJsBuiltin = (spec: string): boolean => {
	if (RUNTIME_BUILTINS.has(spec)) return true;
	const stripped = spec.startsWith("node:") ? spec.slice(5) : spec;
	return isBuiltin(stripped) || isBuiltin(spec);
};

const VIRTUAL_MODULE_PREFIXES = [
	"astro:",
	"virtual:",
	"bun:",
	"file:",
	"http:",
	"https:",
	"jsr:",
	"npm:",
];
const DOCUSAURUS_VIRTUAL_PREFIXES = ["@docusaurus/", "@theme/", "@theme-original/", "@site"];

const hasDocusaurusDependency = (jsDeps: Set<string>): boolean => {
	for (const dep of jsDeps) {
		if (dep.startsWith("@docusaurus/")) return true;
	}
	return false;
};

const isDocusaurusVirtualImport = (spec: string, jsDeps: Set<string>): boolean => {
	if (!hasDocusaurusDependency(jsDeps)) return false;
	return DOCUSAURUS_VIRTUAL_PREFIXES.some((prefix) => spec === prefix || spec.startsWith(prefix));
};

const readWorkspaceGlobs = (pkg: Record<string, unknown>): string[] => {
	const globs: string[] = [];
	const ws = pkg.workspaces;
	if (Array.isArray(ws)) {
		for (const g of ws) if (typeof g === "string") globs.push(g);
	} else if (ws && typeof ws === "object") {
		const pkgs = (ws as Record<string, unknown>).packages;
		if (Array.isArray(pkgs)) {
			for (const g of pkgs) if (typeof g === "string") globs.push(g);
		}
	}
	return globs;
};

const isWaspProjectDirectory = (directory: string): boolean => {
	try {
		if (fs.existsSync(path.join(directory, "main.wasp"))) return true;
		const pkg = readJson(path.join(directory, "package.json")) as Record<string, unknown> | null;
		if (!pkg) return false;
		return readWorkspaceGlobs(pkg).some((glob) => glob.includes("wasp") || glob.includes(".wasp"));
	} catch {
		return false;
	}
};

const isWaspSdkImport = (spec: string, filePath: string, rootDirectory: string): boolean => {
	if (spec !== "wasp" && !spec.startsWith("wasp/")) return false;
	let dir = path.dirname(filePath);
	const root = path.resolve(rootDirectory);
	while (dir.startsWith(root)) {
		if (isWaspProjectDirectory(dir)) return true;
		if (dir === root) break;
		dir = path.dirname(dir);
	}
	return false;
};

const isJsVirtualModule = (
	spec: string,
	jsDeps: Set<string>,
	filePath: string,
	rootDirectory: string,
): boolean => {
	if (VIRTUAL_MODULE_PREFIXES.some((p) => spec.startsWith(p))) return true;
	if (spec === "bun") return true;
	if (spec === "unfonts.css" && jsDeps.has("unplugin-fonts")) return true;
	if (spec.startsWith("~icons/") && jsDeps.has("unplugin-icons")) return true;
	if (isDocusaurusVirtualImport(spec, jsDeps)) return true;
	if (isWaspSdkImport(spec, filePath, rootDirectory)) return true;
	return false;
};

const stripImportQuery = (spec: string): string => {
	const idx = spec.indexOf("?");
	return idx === -1 ? spec : spec.slice(0, idx);
};

// Filter out import-shaped substrings inside template literals or error messages — these chars never appear in real package names.
const TEMPLATE_PLACEHOLDER_RE = /\$\{/;
const isLikelyRealImportSpec = (spec: string): boolean => {
	if (spec.length === 0) return false;
	if (TEMPLATE_PLACEHOLDER_RE.test(spec)) return false;
	if (spec.includes("\\")) return false;
	if (/\s/.test(spec)) return false;
	return true;
};

const packageNameFromImport = (spec: string): string => {
	if (spec.startsWith("@")) {
		const parts = spec.split("/");
		return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : spec;
	}
	return spec.split("/")[0];
};

// The @types/* package providing types for a runtime package: `foo` -> `@types/foo`,
// `@scope/pkg` -> `@types/scope__pkg` (DefinitelyTyped scoped-name convention).
const typesPackageName = (pkg: string): string => {
	if (pkg.startsWith("@types/")) return pkg;
	if (pkg.startsWith("@")) return `@types/${pkg.slice(1).replace("/", "__")}`;
	return `@types/${pkg}`;
};

// Static `import ... from "spec"` anchored to start-of-line so it never matches
// `import { ... } from "x"` written *inside* a string literal in source.
const STATIC_IMPORT_RE = /^\s*import\s+(?:[\w*{},\s]+\s+from\s+)?["']([^"']+)["']/;
// Dynamic `import("spec")` and `require("spec")` can appear mid-line by design.
const DYNAMIC_IMPORT_RE = /(?:import|require)\s*\(\s*["']([^"']+)["']/g;

const extractJsImports = (content: string): { spec: string; line: number }[] => {
	const lines = content.split("\n");
	const results: { spec: string; line: number }[] = [];
	let inTemplateLiteral = false;

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];

		for (let j = 0; j < line.length; j++) {
			if (line[j] === "`" && (j === 0 || line[j - 1] !== "\\")) {
				inTemplateLiteral = !inTemplateLiteral;
			}
		}
		if (inTemplateLiteral) continue;

		const trimmed = line.trim();
		if (trimmed.startsWith("//") || trimmed.startsWith("*")) continue;

		const staticMatch = STATIC_IMPORT_RE.exec(line);
		if (staticMatch && isLikelyRealImportSpec(staticMatch[1])) {
			results.push({ spec: staticMatch[1], line: i + 1 });
		}

		DYNAMIC_IMPORT_RE.lastIndex = 0;
		let dyn: RegExpExecArray | null = DYNAMIC_IMPORT_RE.exec(line);
		while (dyn !== null) {
			if (isLikelyRealImportSpec(dyn[1])) {
				results.push({ spec: dyn[1], line: i + 1 });
			}
			dyn = DYNAMIC_IMPORT_RE.exec(line);
		}
	}
	return results;
};

const extractPyImports = (content: string): { spec: string; line: number }[] => {
	const lines = content.split("\n");
	const results: { spec: string; line: number }[] = [];
	let inDoc: string | null = null;
	let typeCheckIndent = -1;
	for (let i = 0; i < lines.length; i++) {
		const raw = lines[i];
		const line = raw.trim();

		if (inDoc) {
			if (line.includes(inDoc)) inDoc = null;
			continue;
		}
		if (line === "" || line.startsWith("#")) continue;

		// Triple-quoted strings (docstrings, usage examples) hold import-shaped prose, not imports.
		const triples = line.match(/"""|'''/g);
		if (triples) {
			if (triples.length % 2 === 1) inDoc = triples[triples.length - 1];
			continue;
		}

		const indent = raw.length - raw.trimStart().length;
		if (typeCheckIndent >= 0 && indent <= typeCheckIndent) typeCheckIndent = -1;
		// Imports under `if TYPE_CHECKING:` are type-only — often typeshed-internal or dev-only deps.
		if (/^if\s+(?:[\w.]+\.)?TYPE_CHECKING\b/.test(line)) {
			typeCheckIndent = indent;
			continue;
		}
		if (typeCheckIndent >= 0) continue;

		// from X import ... — skip relative imports starting with .
		const fromMatch = line.match(/^from\s+([\w.]+)\s+import\b/);
		if (fromMatch && !fromMatch[1].startsWith(".")) {
			results.push({ spec: fromMatch[1], line: i + 1 });
			continue;
		}
		// import X[, Y as Z, ...]
		const importMatch = line.match(/^import\s+([\w.,\s]+?)(?:\s+as\s+\w+)?\s*$/);
		if (importMatch) {
			for (const part of importMatch[1].split(",")) {
				const cleaned = part.trim().split(/\s+as\s+/)[0];
				if (cleaned && !cleaned.startsWith(".")) {
					results.push({ spec: cleaned, line: i + 1 });
				}
			}
		}
	}
	return results;
};

// Common transitive imports pulled in by unified/remark/docusaurus plugin stacks.
const JS_IMPORT_TO_DECLARATION: Record<string, string[]> = {
	"unist-util-visit": ["unified", "remark-cli", "@mdx-js/react", "@docusaurus/core"],
};

const isTransitiveJsImport = (pkg: string, jsDeps: Set<string>): boolean => {
	const declarations = JS_IMPORT_TO_DECLARATION[pkg];
	return declarations?.some((dep) => jsDeps.has(dep)) ?? false;
};

const isScopedFamilyImport = (spec: string, jsDeps: Set<string>): boolean => {
	if (!spec.startsWith("@")) return false;
	const slash = spec.indexOf("/");
	if (slash === -1) return false;
	const scope = spec.slice(0, slash);
	if (scope === "@types") return false;
	const prefix = `${scope}/`;
	for (const dep of jsDeps) {
		if (dep.startsWith(prefix)) return true;
	}
	return false;
};

const checkJsImport = (
	rawSpec: string,
	jsDeps: Set<string>,
	tsAliasMatchers: AliasMatcher[],
	filePath: string,
	rootDirectory: string,
): string | null => {
	const spec = stripImportQuery(rawSpec);
	if (spec.length === 0) return null;
	if (isJsRelativeOrAbsolute(spec)) return null;
	if (isJsBuiltin(spec)) return null;
	if (isJsVirtualModule(spec, jsDeps, filePath, rootDirectory)) return null;
	if (tsAliasMatchers.some((m) => m(spec))) return null;
	const pkg = packageNameFromImport(spec);
	if (pkg === "@prisma/client" && jsDeps.has("prisma")) return null;
	if (jsDeps.has(pkg)) return null;
	if (isTransitiveJsImport(pkg, jsDeps)) return null;
	if (isScopedFamilyImport(spec, jsDeps)) return null;
	// Allow @types/X if X itself is in deps (the runtime impl) — common pattern.
	if (pkg.startsWith("@types/")) {
		const realPkg = pkg.slice("@types/".length);
		if (jsDeps.has(realPkg)) return null;
	}
	// Type-only imports backed by a declared @types/* package are not hallucinated.
	if (jsDeps.has(typesPackageName(pkg))) return null;
	return pkg;
};

const normalizePyName = (name: string): string => name.toLowerCase().replace(/_/g, "-");

const pyDepSatisfiesImportRoot = (root: string, pyDeps: Set<string>): boolean => {
	const normalized = normalizePyName(root);
	for (const dep of pyDeps) {
		if (dep === normalized || dep.startsWith(`${normalized}-`)) return true;
	}
	return false;
};

const checkPyImport = (spec: string, pyDeps: Set<string>): string | null => {
	const root = spec.split(".")[0];
	if (PYTHON_STDLIB.has(root)) return null;
	if (pyDepSatisfiesImportRoot(root, pyDeps)) return null;
	const normalized = normalizePyName(root);
	const distributions = PYTHON_IMPORT_TO_PIP[root] ?? PYTHON_IMPORT_TO_PIP[normalized];
	if (distributions?.some((dist) => pyDeps.has(normalizePyName(dist)))) return null;
	return root;
};

const isWithinDirectory = (filePath: string, directory: string): boolean => {
	const relative = path.relative(directory, filePath);
	return (
		relative === "" || (!!relative && !relative.startsWith("..") && !path.isAbsolute(relative))
	);
};

const jsDepsForFile = (
	manifest: PackageManifest,
	filePath: string,
	rootDirectory: string,
): Set<string> => {
	const deps = new Set<string>();
	for (const scope of manifest.jsScopes) {
		if (scope.packageName) deps.add(scope.packageName);
	}

	const nearestScope = manifest.jsScopes
		.filter(
			(scope) => scope.directory !== rootDirectory && isWithinDirectory(filePath, scope.directory),
		)
		.sort((a, b) => b.directory.length - a.directory.length)[0];

	if (nearestScope) {
		mergeDeps(deps, nearestScope.jsDeps);
		return deps;
	}

	const rootScope = manifest.jsScopes.find((scope) => scope.directory === rootDirectory);
	if (rootScope) mergeDeps(deps, rootScope.jsDeps);
	else mergeDeps(deps, manifest.jsDeps);
	return deps;
};

const pythonDepsForFile = (
	manifest: PackageManifest,
	filePath: string,
	rootDirectory: string,
): Set<string> | null => {
	const deps = new Set<string>();
	const rootScope = manifest.pyScopes.find((scope) => scope.directory === rootDirectory);
	if (manifest.rootHasPyManifest && rootScope) mergeDeps(deps, rootScope.pyDeps);

	const nestedScope = manifest.pyScopes
		.filter(
			(scope) =>
				scope.directory !== rootDirectory &&
				scope.hasPyManifest &&
				isWithinDirectory(filePath, scope.directory),
		)
		.sort((a, b) => b.directory.length - a.directory.length)[0];
	if (nestedScope) mergeDeps(deps, nestedScope.pyDeps);

	if (!manifest.rootHasPyManifest && !nestedScope) return null;
	if (deps.size === 0 && manifest.pyDeps.size > 0) return manifest.pyDeps;
	return deps;
};

export const detectHallucinatedImports = async (context: EngineContext): Promise<Diagnostic[]> => {
	const rootPkg = readJson(path.join(context.rootDirectory, "package.json"));
	const workspaceDirs = collectWorkspaceDirs(context.rootDirectory, rootPkg);
	const manifest = loadManifest(context.rootDirectory);
	if (!manifest.hasJsManifest && !manifest.hasPyManifest) return [];
	const tsAliasMatchers = manifest.hasJsManifest
		? collectTsPathAliases(context.rootDirectory, workspaceDirs)
		: [];

	const diagnostics: Diagnostic[] = [];
	const files = getSourceFiles(context);

	for (const filePath of files) {
		const ext = path.extname(filePath);
		const isJs = JS_EXTENSIONS.has(ext);
		const isPy = PY_EXTENSIONS.has(ext);
		if (!isJs && !isPy) continue;
		if (isJs && !manifest.hasJsManifest) continue;
		if (isPy && !manifest.hasPyManifest) continue;
		if (isAutoGenerated(filePath)) continue;
		const pyDeps = isPy ? pythonDepsForFile(manifest, filePath, context.rootDirectory) : null;
		if (isPy && !pyDeps) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		const relPath = path.relative(context.rootDirectory, filePath);
		if (isNonProductionPath(relPath)) continue;

		const jsDeps = isJs ? jsDepsForFile(manifest, filePath, context.rootDirectory) : null;
		const imports = isJs ? extractJsImports(content) : extractPyImports(content);
		for (const { spec, line } of imports) {
			const hallucinated = isJs
				? checkJsImport(
						spec,
						jsDeps ?? manifest.jsDeps,
						tsAliasMatchers,
						filePath,
						context.rootDirectory,
					)
				: checkPyImport(spec, pyDeps ?? manifest.pyDeps);
			if (!hallucinated) continue;
			const manifestLabel = isJs ? "package.json" : "requirements.txt / pyproject.toml / Pipfile";
			diagnostics.push({
				filePath: relPath,
				engine: "ai-slop",
				rule: "ai-slop/hallucinated-import",
				severity: "error",
				message: `Imports "${hallucinated}" but it's not declared in ${manifestLabel}${isPy ? " and isn't Python stdlib" : ""}`,
				help: "Most often this is an LLM hallucinating a plausible-sounding package name. Either add the package to your manifest, or correct the import.",
				line,
				column: 1,
				category: "AI Slop",
				fixable: false,
			});
		}
	}

	return diagnostics;
};
