import fs from "node:fs";
import os from "node:os";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFiles, getTestFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

interface UserHomeMatcher {
	expression: RegExp;
	plainPosixPath: boolean;
}

/** Exported for unit tests only (span-overlap performance regression). */
export interface CandidateSpan {
	start: number;
	end: number;
}

/**
 * Final home-root path segments that identify a placeholder or CI service
 * account rather than a real developer machine. Seeding a banned root from
 * one of these would invert the rule: it would flag paths bound to the CI
 * runner instead of paths bound to a real person. Kept as a literal,
 * readable list per the closed-decision-surface rule; extend it by editing
 * this list, not by inferring "looks like a service account" from shape.
 */
const PLACEHOLDER_HOME_SEGMENTS = new Set([
	"runner",
	"runneradmin",
	"user",
	"username",
	"default",
	"defaultuser",
	"example",
	"public",
	"shared",
	"someone",
	"me",
	"your-name",
	"yourname",
]);
const RUNNER_HOME_PREFIX = "runner~";

const PATH_TOKEN_BOUNDARY_CHARACTERS = new Set(['"', "'", "`", "(", ")", "[", ",", ";", "=", ":"]);
const WHITESPACE_CHARACTER = /\s/;
const TOKEN_START_EXPRESSION = String.raw`(?<![^\s"'\`()[\],;=:])`;
const TOKEN_END_EXPRESSION = String.raw`(?=$|[\s"'\`()\]},;:])`;
const TOKEN_REMAINDER_EXPRESSION = String.raw`[^\s"'\`<>]*`;
const WEB_URL_EXPRESSION = String.raw`[Hh][Tt][Tt][Pp][Ss]?:\/\/[^\s"'\`<>]*`;
const FILE_SCHEME_EXPRESSION = "[Ff][Ii][Ll][Ee]:";
const FILE_URL_EXPRESSION = String.raw`${FILE_SCHEME_EXPRESSION}[^\s"'\`<>]*`;
// The `localhost` authority is the standard local-file-URL spelling
// (`file://localhost/...`) and resolves to the same path as the no-authority
// and empty-authority forms. Matched case-insensitively regardless of
// whether the rest of the path is POSIX (case-sensitive) or Windows
// (case-insensitive), since the authority is not part of the path itself.
const LOCALHOST_AUTHORITY_EXPRESSION = "[Ll][Oo][Cc][Aa][Ll][Hh][Oo][Ss][Tt]";

const escapeRegularExpression = (value: string): string =>
	value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const isPathTokenBoundaryCharacter = (character: string | undefined): boolean =>
	character === undefined ||
	WHITESPACE_CHARACTER.test(character) ||
	PATH_TOKEN_BOUNDARY_CHARACTERS.has(character);

const hasWindowsDrivePrefix = (line: string, matchIndex: number): boolean => {
	const driveLetterIndex = matchIndex - 2;
	const driveLetter = line[driveLetterIndex]?.toLowerCase();
	return (
		line[matchIndex - 1] === ":" &&
		driveLetter !== undefined &&
		driveLetter >= "a" &&
		driveLetter <= "z" &&
		isPathTokenBoundaryCharacter(line[driveLetterIndex - 1])
	);
};

const makeHomePathExpression = (homeDirectory: string): UserHomeMatcher | undefined => {
	const normalizedHomeDirectory = homeDirectory.replace(/[\\/]+$/, "");
	if (normalizedHomeDirectory.length === 0) return undefined;

	const drivePath = /^[A-Za-z]:[\\/]/.test(normalizedHomeDirectory);
	const uncPath = /^[\\/]{2}[^\\/]/.test(normalizedHomeDirectory);
	const windowsPath = drivePath || uncPath;
	const separatorExpression = windowsPath ? String.raw`[\\/]+` : String.raw`\/+`;
	const homeSegments = normalizedHomeDirectory
		.split(/[\\/]+/)
		.filter((segment) => segment.length > 0);
	const leadingSeparatorExpression = uncPath
		? String.raw`[\\/]{2,}`
		: normalizedHomeDirectory.startsWith("/")
			? String.raw`\/+`
			: "";
	const rawHomeExpression = `${leadingSeparatorExpression}${homeSegments
		.map(escapeRegularExpression)
		.join(separatorExpression)}`;
	const descendantExpression = `(?:${separatorExpression}${TOKEN_REMAINDER_EXPRESSION})?`;
	const fileHomeExpression = homeSegments.map(escapeRegularExpression).join(String.raw`\/+`);
	// The `localhost` file: URL authority resolves to the local filesystem for
	// POSIX and Windows drive roots, but NOT for UNC roots: there, the authority
	// position names the UNC server itself (`file://server/share/...`), so
	// `file://localhost/server/...` is a different, non-equivalent URL and must
	// not match.
	const localhostFilePathExpression = `${FILE_SCHEME_EXPRESSION}/{2}${LOCALHOST_AUTHORITY_EXPRESSION}/${fileHomeExpression}`;
	const filePathExpression = drivePath
		? `(?:${FILE_SCHEME_EXPRESSION}/{1,3}${fileHomeExpression}|${localhostFilePathExpression})`
		: uncPath
			? `${FILE_SCHEME_EXPRESSION}/{2}${fileHomeExpression}`
			: `(?:(?:${FILE_SCHEME_EXPRESSION}|${FILE_SCHEME_EXPRESSION}/{2})/${fileHomeExpression}|${localhostFilePathExpression})`;
	const expression = [
		WEB_URL_EXPRESSION,
		`(?<filePath>${TOKEN_START_EXPRESSION}${filePathExpression}${descendantExpression}${TOKEN_END_EXPRESSION})`,
		FILE_URL_EXPRESSION,
		`(?<plainPath>${TOKEN_START_EXPRESSION}${rawHomeExpression}${descendantExpression}${TOKEN_END_EXPRESSION})`,
	].join("|");

	return {
		expression: new RegExp(expression, windowsPath ? "gi" : "g"),
		plainPosixPath: !windowsPath,
	};
};

const makeDiagnostic = (filePath: string, line: number, column: number): Diagnostic => ({
	filePath,
	engine: "ai-slop",
	rule: "ai-slop/hardcoded-user-path",
	severity: "warning",
	message: "Hardcoded user-specific home path",
	help: "Resolve user home directories at runtime with a platform API, or inject the path through configuration.",
	line,
	column,
	category: "AI Slop",
	fixable: false,
});

/** Trailing separators trimmed, matching the normalization `makeHomePathExpression` applies. */
const trimTrailingSeparators = (root: string): string => root.replace(/[\\/]+$/, "");

const finalPathSegment = (root: string): string => {
	const segments = trimTrailingSeparators(root)
		.split(/[\\/]+/)
		.filter((segment) => segment.length > 0);
	return segments[segments.length - 1] ?? "";
};

const isPlaceholderHomeRoot = (root: string): boolean => {
	const segment = finalPathSegment(root).toLowerCase();
	return segment.startsWith(RUNNER_HOME_PREFIX) || PLACEHOLDER_HOME_SEGMENTS.has(segment);
};

// Mirrors the drive-root and UNC-root detection in src/config/schema.ts,
// where the same check gates `aiSlop.hardcodedUserPath.bannedRoots` at
// config-load time. This copy is defense in depth for callers that build an
// EngineContext directly (tests, or any future caller) rather than going
// through config loading and its validation.
const isAbsoluteBannedRoot = (root: string): boolean =>
	root.startsWith("/") || /^[A-Za-z]:[\\/]/.test(root) || /^[\\/]{2}[^\\/]/.test(root);

/**
 * A root with no leading separator (a bare word like "alice", or a relative
 * path like "home/alice") builds a matcher with no path-boundary
 * requirement, so it would flag ordinary identifiers instead of hardcoded
 * paths - exactly the false positive this rule exists to avoid. Rejected
 * entries are dropped, not silently ignored: each one is reported on stderr
 * naming the offending value, so a config typo does not read as "this root
 * is protected" when it is not.
 */
const filterAbsoluteBannedRoots = (roots: string[]): string[] => {
	const valid: string[] = [];
	for (const root of roots) {
		if (isAbsoluteBannedRoot(root)) {
			valid.push(root);
			continue;
		}
		process.stderr.write(
			`  ⚠ Ignoring aiSlop.hardcodedUserPath.bannedRoots entry ${JSON.stringify(root)}: ` +
				`not an absolute path (POSIX "/...", a Windows drive root "C:\\..." or "C:/...", ` +
				`or a UNC root "\\\\server\\share...").\n`,
		);
	}
	return valid;
};

/**
 * Configured roots, plus `os.homedir()` as a default seed unless that seed's
 * final segment names a placeholder or CI service account. Deduplicated on
 * the same trailing-separator normalization the matcher itself applies, so a
 * root listed twice (once from config, once as the seed) yields one matcher.
 */
const resolveBannedRoots = (context: EngineContext): string[] => {
	const configuredRoots = filterAbsoluteBannedRoots(
		context.config.aiSlop?.hardcodedUserPath?.bannedRoots ?? [],
	);
	const seedHomeDirectory = os.homedir();
	const candidateRoots = isPlaceholderHomeRoot(seedHomeDirectory)
		? configuredRoots
		: [...configuredRoots, seedHomeDirectory];

	const seen = new Set<string>();
	const roots: string[] = [];
	for (const root of candidateRoots) {
		const normalized = trimTrailingSeparators(root);
		if (normalized.length === 0 || seen.has(normalized)) continue;
		seen.add(normalized);
		roots.push(normalized);
	}
	return roots;
};

const collectCandidateSpans = (line: string, matchers: UserHomeMatcher[]): CandidateSpan[] => {
	const spans: CandidateSpan[] = [];
	for (const matcher of matchers) {
		for (const match of line.matchAll(matcher.expression)) {
			const groups = match.groups as { filePath?: string; plainPath?: string };
			if (groups.filePath === undefined && groups.plainPath === undefined) continue;
			const matchIndex = match.index as number;
			if (
				matcher.plainPosixPath &&
				groups.plainPath !== undefined &&
				hasWindowsDrivePrefix(line, matchIndex)
			) {
				continue;
			}
			spans.push({ start: matchIndex, end: matchIndex + match[0].length });
		}
	}
	return spans;
};

/**
 * Drops any span fully contained in another so one hardcoded path yields one
 * diagnostic even when configured roots overlap (e.g. `/home/alice` and
 * `/home/alice/project` both banned). Sorted by ascending start, then
 * descending end, every span already kept has a start at or before the
 * current one, so a single running maximum kept end position is enough to
 * decide containment: if the current span's end does not exceed that
 * maximum, some earlier kept span already covers it. This is a single O(n)
 * sweep after the sort, not a scan against every previously kept span.
 *
 * Exported for unit tests only (span-overlap performance regression).
 */
export const dropContainedSpans = (spans: CandidateSpan[]): CandidateSpan[] => {
	const sorted = [...spans].sort((a, b) => a.start - b.start || b.end - a.end);
	const kept: CandidateSpan[] = [];
	let maximumKeptEnd = -1;
	for (const span of sorted) {
		if (span.end <= maximumKeptEnd) continue;
		kept.push(span);
		maximumKeptEnd = span.end;
	}
	return kept;
};

const scanLine = (
	line: string,
	filePath: string,
	lineNumber: number,
	matchers: UserHomeMatcher[],
): Diagnostic[] => {
	const spans = dropContainedSpans(collectCandidateSpans(line, matchers));
	return spans.map((span) => makeDiagnostic(filePath, lineNumber, span.start + 1));
};

export const detectHardcodedUserPaths = async (context: EngineContext): Promise<Diagnostic[]> => {
	const matchers: UserHomeMatcher[] = [];
	for (const root of resolveBannedRoots(context)) {
		const matcher = makeHomePathExpression(root);
		if (matcher !== undefined) matchers.push(matcher);
	}
	if (matchers.length === 0) return [];

	const diagnostics: Diagnostic[] = [];
	const files = new Set([...getSourceFiles(context), ...getTestFiles(context)]);

	for (const filePath of files) {
		if (isAutoGenerated(filePath)) continue;
		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const relativePath = relativePosix(context.rootDirectory, filePath);
		const normalizedContent = content.replaceAll("\r\n", "\n");
		const lines = normalizedContent.split("\n");
		for (let index = 0; index < lines.length; index++) {
			diagnostics.push(...scanLine(lines[index], relativePath, index + 1, matchers));
		}
	}

	return diagnostics;
};
