import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFilesWithExtras, isAutoGenerated } from "../../utils/source-files.js";
import { isAislopDirectiveLine } from "../../utils/suppress.js";
import type { Diagnostic, EngineContext } from "../types.js";

/**
 * Prose, docs, and config files carry the tell just as often as code, so this rule
 * scans well past the compiled source extensions.
 */
const PUNCTUATION_EXTRA_EXTENSIONS = [
	".md",
	".markdown",
	".mdx",
	".rst",
	".adoc",
	".txt",
	".yml",
	".yaml",
	".toml",
	".json",
	".jsonc",
	".ini",
	".cfg",
	".sh",
	".bash",
	".zsh",
	".ps1",
	".psm1",
	".bat",
	".cmd",
	".html",
	".css",
	".scss",
	".vue",
	".svelte",
	".astro",
	".sql",
];

/**
 * Dependency lockfiles are machine-written data, never authored prose, and a single
 * transitive package description can add hundreds of findings nobody can act on.
 */
const LOCKFILE_NAMES = new Set([
	"package-lock.json",
	"npm-shrinkwrap.json",
	"pnpm-lock.yaml",
	"bun.lock",
	"uv.lock",
	"poetry.lock",
	"cargo.lock",
	"composer.lock",
	"gemfile.lock",
	"pdm.lock",
	"deno.lock",
]);

interface WatchedCharacter {
	codePoint: number;
	name: string;
	replacement: string;
}

const character = (codePoint: number, name: string, replacement: string): WatchedCharacter => ({
	codePoint,
	name,
	replacement,
});

/**
 * The dash family. Built from code points rather than literals so aislop scanning its
 * own source does not report this table as a finding.
 */
const DASH_CHARACTERS: WatchedCharacter[] = [
	character(0x2014, "em dash", "-"),
	character(0x2013, "en dash", "-"),
	character(0x2015, "horizontal bar", "-"),
	character(0x2012, "figure dash", "-"),
	character(0x2011, "non-breaking hyphen", "-"),
	character(0x2010, "unicode hyphen", "-"),
	character(0x2212, "minus sign", "-"),
];

/** Quotes, ellipsis, arrows, and invisible spacing that ASCII already covers. */
const SMART_CHARACTERS: WatchedCharacter[] = [
	character(0x2018, "left single quotation mark", "'"),
	character(0x2019, "right single quotation mark", "'"),
	character(0x201a, "single low quotation mark", "'"),
	character(0x201c, "left double quotation mark", '"'),
	character(0x201d, "right double quotation mark", '"'),
	character(0x201e, "double low quotation mark", '"'),
	character(0x2026, "horizontal ellipsis", "..."),
	character(0x2192, "rightwards arrow", "->"),
	character(0x2190, "leftwards arrow", "<-"),
	character(0x21d2, "rightwards double arrow", "=>"),
	character(0x00a0, "non-breaking space", "a plain space"),
	character(0x202f, "narrow non-breaking space", "a plain space"),
	character(0x200b, "zero width space", "nothing"),
];

interface WatchedFamily {
	rule: string;
	category: string;
	characters: Map<number, WatchedCharacter>;
	summary: string;
}

const toMap = (characters: WatchedCharacter[]): Map<number, WatchedCharacter> =>
	new Map(characters.map((entry) => [entry.codePoint, entry]));

const WATCHED_FAMILIES: WatchedFamily[] = [
	{
		rule: "ai-slop/em-dash",
		category: "AI Slop",
		characters: toMap(DASH_CHARACTERS),
		summary: "dash",
	},
	{
		rule: "ai-slop/smart-punctuation",
		category: "AI Slop",
		characters: toMap(SMART_CHARACTERS),
		summary: "punctuation",
	},
];

const MAX_ASCII_CODE_POINT = 127;

/** Whole-file fast path: most files in a repo are pure ASCII and need no line walk. */
const hasNonAscii = (content: string): boolean => {
	for (let index = 0; index < content.length; index++) {
		if (content.charCodeAt(index) > MAX_ASCII_CODE_POINT) return true;
	}
	return false;
};

const isLockfile = (relativePath: string): boolean =>
	LOCKFILE_NAMES.has(path.basename(relativePath).toLowerCase());

interface LineHit {
	entry: WatchedCharacter;
	column: number;
	count: number;
}

/**
 * Returns the first offending character on the line plus the total number of hits from
 * the same family, so one line yields one finding instead of one per character.
 */
const scanLine = (line: string, family: WatchedFamily): LineHit | null => {
	let first: WatchedCharacter | null = null;
	let firstColumn = 0;
	let count = 0;
	let column = 0;

	for (const char of line) {
		column += 1;
		const entry = family.characters.get(char.codePointAt(0) ?? 0);
		if (!entry) continue;
		count += 1;
		if (!first) {
			first = entry;
			firstColumn = column;
		}
	}

	if (!first) return null;
	return { entry: first, column: firstColumn, count };
};

const buildMessage = (hit: LineHit, family: WatchedFamily): string => {
	const extra = hit.count > 1 ? ` (${hit.count} on this line)` : "";
	return `Non-ASCII ${family.summary}: ${hit.entry.name}${extra}`;
};

const DIRECTIVE_PREFIX = "aislop-ignore-";
const DIRECTIVE_REASON_SEPARATOR = "--";

/**
 * Blanks out only the trailing reason of a suppression directive, which is human prose
 * that may legitimately name the character it silences. The rest of the line is still
 * scanned, so a directive for an unrelated rule cannot smuggle punctuation through.
 */
const stripDirectiveReason = (line: string): string => {
	if (!isAislopDirectiveLine(line)) return line;
	const directiveStart = line.indexOf(DIRECTIVE_PREFIX);
	if (directiveStart === -1) return line;
	const separator = line.indexOf(DIRECTIVE_REASON_SEPARATOR, directiveStart);
	return separator === -1 ? line : line.slice(0, separator);
};

const buildHelp = (hit: LineHit): string =>
	`Replace with ${hit.entry.replacement}, or keep it deliberately with an aislop-ignore-line / aislop-ignore-file directive naming the rule.`;

export const detectNonAsciiPunctuation = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFilesWithExtras(context, PUNCTUATION_EXTRA_EXTENSIONS);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		const relativePath = relativePosix(context.rootDirectory, filePath);
		if (isLockfile(relativePath)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}
		if (!hasNonAscii(content)) continue;
		if (isAutoGenerated(filePath)) continue;

		const lines = content.split(/\r?\n/);
		for (let index = 0; index < lines.length; index++) {
			const line = stripDirectiveReason(lines[index]);

			for (const family of WATCHED_FAMILIES) {
				const hit = scanLine(line, family);
				if (!hit) continue;

				diagnostics.push({
					filePath: relativePath,
					engine: "ai-slop",
					rule: family.rule,
					severity: "info",
					message: buildMessage(hit, family),
					help: buildHelp(hit),
					line: index + 1,
					column: hit.column,
					category: family.category,
					fixable: false,
				});
			}
		}
	}

	return diagnostics;
};
