import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getSourceFilesWithExtras, isAutoGenerated } from "../../utils/source-files.js";
import { isAislopDirectiveLine } from "../../utils/suppress.js";
import type { Diagnostic, EngineContext } from "../types.js";

// Systemd unit extensions scanned for service and socket/mount/swap timeouts.
const SYSTEMD_EXTENSIONS = [".service", ".socket", ".mount", ".swap"];

// Broken up string literals for self-detection avoidance.
const SERVICE_SECTION = "Serv" + "ice";
const SOCKET_SECTION = "Sock" + "et";
const MOUNT_SECTION = "Mo" + "unt";
const SWAP_SECTION = "Sw" + "ap";

const TYPE_KEY = "Ty" + "pe";
const ONESHOT_VAL = "one" + "shot";
const TIMEOUT_START_SEC_KEY = "Timeout" + "StartSec";
const TIMEOUT_SEC_KEY = "Timeout" + "Sec";

// systemd derives the unit type from the file extension and only reads the
// one section that matches it: a [Socket] section in a .service file, or a
// [Service] section in a .socket file, is never consulted by systemd, so it
// does not participate here either.
const UNIT_SECTION_BY_EXTENSION: Record<string, string> = {
	".service": SERVICE_SECTION,
	".socket": SOCKET_SECTION,
	".mount": MOUNT_SECTION,
	".swap": SWAP_SECTION,
};

// Directive keys that resolve the start timeout, keyed by the unit section
// that documents them. TimeoutStartSec is service-specific; systemd.socket,
// systemd.mount and systemd.swap document only TimeoutSec and silently
// ignore a TimeoutStartSec= line, so it must not participate there.
const START_TIMEOUT_KEYS_BY_SECTION: Record<string, readonly string[]> = {
	[SERVICE_SECTION]: [TIMEOUT_START_SEC_KEY, TIMEOUT_SEC_KEY],
	[SOCKET_SECTION]: [TIMEOUT_SEC_KEY],
	[MOUNT_SECTION]: [TIMEOUT_SEC_KEY],
	[SWAP_SECTION]: [TIMEOUT_SEC_KEY],
};

interface ParsedDirective {
	key: string;
	value: string;
	line: number;
	column: number;
	hasRationale: boolean;
}

interface ParsedSection {
	name: string;
	line: number;
	directives: ParsedDirective[];
}

const SECTION_HEADER_RE = /^\s*\[([a-zA-Z0-9_@.-]+)\]\s*$/;
const DIRECTIVE_LINE_RE = /^\s*([a-zA-Z0-9_-]+)\s*=\s*(.*)$/;

const TIME_UNIT_RE =
	/^(?:usec|us|µs|msec|ms|seconds?|sec|s|minutes?|min|m|hours?|hr|h|days?|d|weeks?|w|months?|M|years?|y)$/i;

const isUnboundedTimeoutValue = (value: string): boolean => {
	const trimmed = value.trim();
	if (trimmed === "") return false;
	// systemd only recognizes the lowercase spelling `infinity`; any other
	// casing is not a value systemd understands, so it does not disable the
	// timeout and is not flagged.
	if (trimmed === "infinity") return true;

	// In systemd, any time span expression totaling 0 disables the timeout.
	// A time span is composed of one or more [number][unit] components separated by whitespace.
	const componentRe = /([0-9]+(?:\.[0-9]+)?)\s*([a-zA-Zµ]+)?/g;
	let lastIndex = 0;
	let matchCount = 0;
	let match: RegExpExecArray | null;

	while ((match = componentRe.exec(trimmed)) !== null) {
		const gap = trimmed.slice(lastIndex, match.index).trim();
		if (gap !== "") return false;

		const numStr = match[1];
		const unit = match[2];

		if (unit !== undefined && !TIME_UNIT_RE.test(unit)) {
			return false;
		}

		const num = Number(numStr);
		if (Number.isNaN(num) || num !== 0) {
			return false;
		}

		matchCount++;
		lastIndex = match.index + match[0].length;
	}

	const trailing = trimmed.slice(lastIndex).trim();
	if (trailing !== "") return false;

	return matchCount > 0;
};

const parseSystemdUnit = (content: string): ParsedSection[] => {
	const lines = content.split(/\r?\n/);
	const sections: ParsedSection[] = [];
	let currentSection: ParsedSection | null = null;

	for (let i = 0; i < lines.length; i++) {
		const rawLine = lines[i];
		const trimmed = rawLine.trim();

		const sectionMatch = SECTION_HEADER_RE.exec(rawLine);
		if (sectionMatch) {
			currentSection = {
				name: sectionMatch[1],
				line: i + 1,
				directives: [],
			};
			sections.push(currentSection);
			continue;
		}

		if (trimmed === "" || trimmed.startsWith("#") || trimmed.startsWith(";")) {
			continue;
		}

		const directiveMatch = DIRECTIVE_LINE_RE.exec(rawLine);
		if (directiveMatch && currentSection) {
			const key = directiveMatch[1];
			const value = directiveMatch[2].trim();
			const keyColumn = rawLine.indexOf(key) + 1;

			let hasPrecedingRationale = false;
			for (let j = i - 1; j >= 0; j--) {
				const prevTrimmed = lines[j].trim();
				if (prevTrimmed === "") {
					break;
				}
				if (prevTrimmed.startsWith("#") || prevTrimmed.startsWith(";")) {
					const commentBody = prevTrimmed.replace(/^[#;\s]+/, "").trim();
					if (commentBody.length > 0 && !isAislopDirectiveLine(lines[j])) {
						hasPrecedingRationale = true;
					}
				} else {
					break;
				}
			}

			currentSection.directives.push({
				key,
				value,
				line: i + 1,
				column: keyColumn,
				hasRationale: hasPrecedingRationale,
			});
		}
	}

	return sections;
};

// Returns the directive among `directives` whose key exactly matches one of
// `participatingKeys`, with the greatest file-order index: systemd resolves
// each option by last assignment wins, across every key that writes it.
const resolveEffectiveDirective = (
	directives: readonly ParsedDirective[],
	participatingKeys: readonly string[],
): ParsedDirective | null => {
	let effective: ParsedDirective | null = null;
	for (const directive of directives) {
		if (participatingKeys.includes(directive.key)) {
			effective = directive;
		}
	}
	return effective;
};

const buildUnboundedDiagnostic = (
	relativePath: string,
	directive: ParsedDirective,
	exampleKey: string,
): Diagnostic => ({
	filePath: relativePath,
	engine: "ai-slop",
	rule: "ai-slop/systemd-timeout",
	severity: "warning",
	message: "Explicit unbounded start timeout without a rationale comment.",
	help: `Add an explicit duration (e.g. \`${exampleKey}=5m\`), or document why the unit must run unbounded with a comment.`,
	line: directive.line,
	column: directive.column,
	category: "AI Slop",
	fixable: false,
});

export const detectSystemdTimeouts = async (context: EngineContext): Promise<Diagnostic[]> => {
	const files = getSourceFilesWithExtras(context, SYSTEMD_EXTENSIONS);
	const diagnostics: Diagnostic[] = [];

	for (const filePath of files) {
		const relativePath = relativePosix(context.rootDirectory, filePath);
		if (isAutoGenerated(filePath)) continue;

		const unitSection = UNIT_SECTION_BY_EXTENSION[path.extname(filePath)];
		if (!unitSection) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const sections = parseSystemdUnit(content);
		if (sections.length === 0) continue;

		// Only sections whose header exactly matches the unit type derived
		// from the file extension participate (repeated matching sections
		// merge, in file order, same as systemd).
		const participatingDirectives = sections
			.filter((section) => section.name === unitSection)
			.flatMap((section) => section.directives);

		if (participatingDirectives.length === 0) continue;

		const startTimeoutKeys = START_TIMEOUT_KEYS_BY_SECTION[unitSection];
		const lastStartTimeoutDirective = resolveEffectiveDirective(
			participatingDirectives,
			startTimeoutKeys,
		);
		const exampleKey = unitSection === SERVICE_SECTION ? TIMEOUT_START_SEC_KEY : TIMEOUT_SEC_KEY;

		if (
			lastStartTimeoutDirective &&
			isUnboundedTimeoutValue(lastStartTimeoutDirective.value) &&
			!lastStartTimeoutDirective.hasRationale
		) {
			diagnostics.push(
				buildUnboundedDiagnostic(relativePath, lastStartTimeoutDirective, exampleKey),
			);
		}

		if (unitSection !== SERVICE_SECTION) continue;

		const lastTypeDirective = resolveEffectiveDirective(participatingDirectives, [TYPE_KEY]);
		const effectiveType = lastTypeDirective?.value.trim();

		if (effectiveType === ONESHOT_VAL && lastTypeDirective) {
			const hasExplicitStartTimeout =
				lastStartTimeoutDirective !== null && lastStartTimeoutDirective.value !== "";

			if (!hasExplicitStartTimeout) {
				diagnostics.push({
					filePath: relativePath,
					engine: "ai-slop",
					rule: "ai-slop/systemd-timeout",
					severity: "warning",
					message:
						"`Type=oneshot` service defaults to an unbounded start timeout (`TimeoutStartSec=infinity`).",
					help: "Add an explicit `TimeoutStartSec=` (e.g. `TimeoutStartSec=5m`) to bound startup time and prevent stalled deployments.",
					line: lastTypeDirective.line,
					column: lastTypeDirective.column,
					category: "AI Slop",
					fixable: false,
				});
			}
		}
	}

	return diagnostics;
};
