import fs from "node:fs";
import path from "node:path";
import { relativePosix } from "../../utils/paths.js";
import { getTestFiles, isAutoGenerated } from "../../utils/source-files.js";
import { maskStringsAndComments } from "../../utils/source-masker.js";
import type { EngineContext } from "../types.js";

// Extensions the two timing rules cover. Every entry has string- and
// comment-masking support in source-masker (so a spelling quoted inside a
// fixture never reads as code) and, outside Python, delimits blocks with
// braces, which is what makes the enclosing-loop question below decidable.
// Java, Rust, and Ruby are deliberately absent: the first two have no masker,
// and Ruby closes blocks with `end` rather than a brace.
const TIMING_EXTENSIONS = new Set([
	".ts",
	".tsx",
	".js",
	".jsx",
	".mjs",
	".cjs",
	".py",
	".cs",
	".go",
	".php",
	".c",
	".cc",
	".cpp",
	".cxx",
	".h",
	".hh",
	".hpp",
	".hxx",
]);

export interface MaskedTestFile {
	readonly relativePath: string;
	readonly extension: string;
	// String and comment interiors blanked, length preserving, so offsets into
	// `masked` line up with the original source.
	readonly masked: string;
	readonly lines: string[];
	readonly lineOffsets: number[];
}

export const readMaskedTestFiles = (context: EngineContext): MaskedTestFile[] => {
	const files: MaskedTestFile[] = [];
	for (const filePath of getTestFiles(context)) {
		if (isAutoGenerated(filePath)) continue;
		const extension = path.extname(filePath).toLowerCase();
		if (!TIMING_EXTENSIONS.has(extension)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const masked = maskStringsAndComments(content, extension);
		const lines = masked.split("\n");
		const lineOffsets: number[] = [];
		let offset = 0;
		for (const line of lines) {
			lineOffsets.push(offset);
			offset += line.length + 1;
		}
		files.push({
			relativePath: relativePosix(context.rootDirectory, filePath),
			extension,
			masked,
			lines,
			lineOffsets,
		});
	}
	return files;
};

const LOOP_HEADER_RE = /^(?:for|while|do|foreach|loop)\b/;
const PYTHON_LOOP_RE = /^(?:async\s+)?(?:for|while)\b/;

const startsLoopHeader = (text: string): boolean =>
	LOOP_HEADER_RE.test(text.trim().replace(/^else\s+/, ""));

// Start of the header text that precedes a block-opening brace: everything back
// to the nearest statement boundary outside of parentheses or brackets. The
// depth counter is what keeps a C-style `for (index = 0; index < n; index++)`
// header intact, since its semicolons sit inside the loop's own parentheses.
const headerStartIndex = (content: string, braceIndex: number): number => {
	let depth = 0;
	for (let index = braceIndex - 1; index >= 0; index--) {
		const character = content[index];
		if (character === ")" || character === "]") {
			depth++;
			continue;
		}
		if (character === "(" || character === "[") {
			if (depth > 0) depth--;
			continue;
		}
		if (depth === 0 && (character === ";" || character === "{" || character === "}")) {
			return index + 1;
		}
	}
	return 0;
};

// Walks outward through every block that encloses `offset` and asks one closed
// question of each: does its header begin with a loop keyword? Balanced `}`/`{`
// pairs passed on the way out are inner blocks that have already closed.
const isInsideBraceLoop = (content: string, offset: number): boolean => {
	let depth = 0;
	for (let index = offset - 1; index >= 0; index--) {
		const character = content[index];
		if (character === "}") {
			depth++;
			continue;
		}
		if (character !== "{") continue;
		if (depth > 0) {
			depth--;
			continue;
		}
		if (startsLoopHeader(content.slice(headerStartIndex(content, index), index))) return true;
	}
	return false;
};

// A loop whose body is a single unbraced statement leaves no brace for the walk
// above to find, so the one preceding statement is checked directly. A header
// containing a brace already opened a block and is handled by isInsideBraceLoop.
const followsUnbracedLoopHeader = (
	lines: string[],
	lineIndex: number,
	columnIndex: number,
): boolean => {
	const prefix = lines[lineIndex].slice(0, columnIndex);
	if (!prefix.includes("{") && startsLoopHeader(prefix)) return true;
	for (let index = lineIndex - 1; index >= 0; index--) {
		const trimmed = lines[index].trim();
		if (trimmed === "") continue;
		return !trimmed.includes("{") && startsLoopHeader(trimmed);
	}
	return false;
};

// Python's block structure is its indentation, so the enclosing headers are the
// lines above with strictly smaller indentation, read outward until column zero.
const isInsidePythonLoop = (lines: string[], lineIndex: number): boolean => {
	const indentWidth = (line: string): number => line.length - line.trimStart().length;
	let currentIndent = indentWidth(lines[lineIndex]);
	for (let index = lineIndex - 1; index >= 0 && currentIndent > 0; index--) {
		const line = lines[index];
		const trimmed = line.trim();
		if (trimmed === "" || trimmed.startsWith("#")) continue;
		const indent = indentWidth(line);
		if (indent >= currentIndent) continue;
		if (PYTHON_LOOP_RE.test(trimmed)) return true;
		currentIndent = indent;
	}
	return false;
};

// A delay inside a loop is a polling interval, which is the recommended shape
// for an asynchronous wait rather than the fixed sleep the rule reports.
export const isInsideLoop = (
	file: MaskedTestFile,
	lineIndex: number,
	columnIndex: number,
): boolean => {
	if (file.extension === ".py") return isInsidePythonLoop(file.lines, lineIndex);
	return (
		isInsideBraceLoop(file.masked, file.lineOffsets[lineIndex] + columnIndex) ||
		followsUnbracedLoopHeader(file.lines, lineIndex, columnIndex)
	);
};
